/** Rotas estáticas públicas de App.tsx — o mapa E2E as abre de verdade. */
export const PUBLIC_STATIC_PATHS = [
  "/",
  "/busca",
  "/historias",
  "/memorias-documentais",
  "/servicos",
  "/comunidade",
  "/sobre",
  "/coberturas",
  "/documentarios",
  "/projetos",
  "/territorios",
  "/rede",
  "/rede/profissionais",
  "/rede/originar",
  "/fotografos",
  "/acervo",
  "/fotografia-documental",
  "/contrate-sua-cobertura",
  "/planejar-um-registro",
  "/contato",
  "/apoie-uma-memoria",
  "/licenciar-midia",
  "/instituicoes",
  "/agenda",
  "/memorias",
  "/cuidado-e-consentimento",
  "/acompanhar-acolhimento",
  "/conheca-a-oju",
  "/termos-de-uso",
  "/privacidade",
  "/ser-parceiro",
] as const;

/** Páginas comunitárias que disparam queries com escrita conhecida. Abrir como humano; não tratar como GET inocente. */
export const WRITE_ON_READ_PUBLIC_PATHS = ["/comunidade", "/instituicoes", "/agenda"] as const;

export const ADMIN_STATIC_PATHS = [
  "/admin",
  "/admin/guia",
  "/admin/canal",
  "/admin/publicacoes",
  "/admin/frentes",
  "/admin/taxonomias",
  "/admin/territorios",
  "/admin/fotografos",
  "/admin/midias",
  "/admin/destaques",
  "/admin/miniclipes",
  "/admin/equipes",
  "/admin/solicitacoes",
  "/admin/oportunidades",
  "/admin/producoes",
  "/admin/notificacoes-rede",
  "/admin/comercial-rede",
  "/admin/receitas",
  "/admin/comunidade",
  "/admin/nova-instituicao",
  "/admin/visibilidade-institucional",
  "/admin/colaboradores",
  "/admin/denuncias",
  "/admin/candidaturas",
  "/admin/nova-memoria-oral",
  "/admin/notificacoes-acolhimento",
  "/admin/revisar-memorias",
  "/admin/distribuicoes-comunidade",
  "/admin/contratos",
  "/admin/configuracoes",
  "/admin/conteudo-portal",
  "/admin/anuncios",
  "/admin/ganhos",
  "/admin/politicas-comerciais",
  "/admin/avisos-repasse",
  "/admin/parceiros",
  "/admin/lixeira-editorial",
  "/admin/lixeira-midias",
  "/admin/retencao",
  "/admin/pendencias",
  "/admin/auditoria",
] as const;

/** Abrir dispara expire/open de Opportunity ou visibilidade institucional. */
export const WRITE_ON_READ_ADMIN_PATHS = [
  "/admin/oportunidades",
  "/admin/comunidade",
  "/admin/visibilidade-institucional",
] as const;
