export const siteDestinations = [
  {
    id: "historias",
    label: "Histórias",
    publicHref: "/historias",
    adminHref: "/admin/publicacoes?tipo=História",
    action: "editorial" as const,
    contentKind: "História" as const,
    how: "Crie, complete texto e capa, publique no site. Aparece em Histórias.",
  },
  {
    id: "coberturas",
    label: "Coberturas",
    publicHref: "/coberturas",
    adminHref: "/admin/publicacoes?tipo=Cobertura",
    action: "editorial" as const,
    contentKind: "Cobertura" as const,
    how: "Crie, ligue fotos e território, publique no site. Aparece em Coberturas.",
  },
  {
    id: "documentarios",
    label: "Documentários",
    publicHref: "/documentarios",
    adminHref: "/admin/publicacoes?tipo=Documentário",
    action: "editorial" as const,
    contentKind: "Documentário" as const,
    how: "Crie, adicione materiais, publique no site. Aparece em Documentários.",
  },
  {
    id: "projetos",
    label: "Projetos",
    publicHref: "/projetos",
    adminHref: "/admin/publicacoes?tipo=Projeto",
    action: "editorial" as const,
    contentKind: "Projeto" as const,
    how: "Crie, complete texto e fotos, publique no site. Aparece em Projetos.",
  },
  {
    id: "fotografia-documental",
    label: "Fotografia documental",
    publicHref: "/fotografia-documental",
    adminHref: "/admin/publicacoes?tipo=Fotografia%20documental",
    action: "editorial" as const,
    contentKind: "Fotografia documental" as const,
    how: "Crie, ligue o território, anexe até 5 fotos e publique no site.",
  },
  {
    id: "territorios",
    label: "Territórios",
    publicHref: "/territorios",
    adminHref: "/admin/territorios",
    action: "link" as const,
    contentKind: null,
    how: "Cadastre o território e ligue conteúdos. Visibilidade no mapa é opcional.",
  },
  {
    id: "fotografos",
    label: "Fotógrafos",
    publicHref: "/fotografos",
    adminHref: "/admin/fotografos",
    action: "link" as const,
    contentKind: null,
    how: "Cadastre nome e apresentação. Publique no site. Crédito nas fotos vale mesmo sem ficha.",
  },
  {
    id: "instituicoes",
    label: "Instituições",
    publicHref: "/instituicoes",
    adminHref: "/admin/comunidade?aba=instituicoes",
    action: "link" as const,
    contentKind: null,
    how: "Crie o perfil com consentimento e clique em Publicar no site.",
  },
  {
    id: "agenda",
    label: "Agenda",
    publicHref: "/agenda",
    adminHref: "/admin/comunidade?aba=agenda",
    action: "link" as const,
    contentKind: null,
    how: "Crie o encontro, autorize e publique na Agenda.",
  },
  {
    id: "memorias",
    label: "Memórias",
    publicHref: "/memorias",
    adminHref: "/admin/comunidade?aba=memorias",
    action: "link" as const,
    contentKind: null,
    how: "Registre com consentimento e publique no site.",
  },
  {
    id: "acervo",
    label: "Acervo",
    publicHref: "/acervo",
    adminHref: "/admin/midias",
    action: "link" as const,
    contentKind: null,
    how: "Envie com crédito e autorização. O site usa o que estiver ligado a conteúdo publicado.",
  },
] as const;

export type SiteDestination = (typeof siteDestinations)[number];
