export const siteDestinations = [
  {
    id: "historias",
    label: "Histórias",
    publicHref: "/historias",
    adminHref: "/admin/publicacoes?tipo=História",
    action: "editorial" as const,
    contentKind: "História" as const,
    how: "Crie, revise, aprove e publique. Aparece em Histórias.",
  },
  {
    id: "coberturas",
    label: "Coberturas",
    publicHref: "/coberturas",
    adminHref: "/admin/publicacoes?tipo=Cobertura",
    action: "editorial" as const,
    contentKind: "Cobertura" as const,
    how: "Crie, vincule fotos, revise, aprove e publique. Aparece em Coberturas.",
  },
  {
    id: "documentarios",
    label: "Documentários",
    publicHref: "/documentarios",
    adminHref: "/admin/publicacoes?tipo=Documentário",
    action: "editorial" as const,
    contentKind: "Documentário" as const,
    how: "Crie, adicione materiais, revise, aprove e publique. Aparece em Documentários.",
  },
  {
    id: "projetos",
    label: "Projetos",
    publicHref: "/projetos",
    adminHref: "/admin/publicacoes?tipo=Projeto",
    action: "editorial" as const,
    contentKind: "Projeto" as const,
    how: "Crie o rascunho, complete texto e fotos, envie para revisão, aprove e publique em Projetos.",
  },
  {
    id: "fotografia-documental",
    label: "Fotografia documental",
    publicHref: "/fotografia-documental",
    adminHref: "/admin/publicacoes?tipo=Fotografia%20documental",
    action: "editorial" as const,
    contentKind: "Fotografia documental" as const,
    how: "Crie a coleção, ligue o território, anexe até 5 fotos com data, local e biografia, revise e publique.",
  },
  {
    id: "territorios",
    label: "Territórios",
    publicHref: "/territorios",
    adminHref: "/admin/territorios",
    action: "link" as const,
    contentKind: null,
    how: "Cadastre o território, a visibilidade no mapa e publique conteúdos ligados a ele.",
  },
  {
    id: "fotografos",
    label: "Fotógrafos",
    publicHref: "/fotografos",
    adminHref: "/admin/fotografos",
    action: "link" as const,
    contentKind: null,
    how: "Cadastre a ficha, marque visível no portal. O crédito nas fotos continua valendo mesmo sem ficha pública.",
  },
  {
    id: "instituicoes",
    label: "Instituições",
    publicHref: "/instituicoes",
    adminHref: "/admin/comunidade?aba=instituicoes",
    action: "link" as const,
    contentKind: null,
    how: "Crie o perfil, registre o consentimento e clique em Publicar.",
  },
  {
    id: "agenda",
    label: "Agenda",
    publicHref: "/agenda",
    adminHref: "/admin/comunidade?aba=agenda",
    action: "link" as const,
    contentKind: null,
    how: "Crie o encontro, confirme a autorização e publique na Agenda.",
  },
  {
    id: "memorias",
    label: "Memórias",
    publicHref: "/memorias",
    adminHref: "/admin/comunidade?aba=memorias",
    action: "link" as const,
    contentKind: null,
    how: "Registre a memória oral com consentimento e publique.",
  },
  {
    id: "acervo",
    label: "Acervo",
    publicHref: "/acervo",
    adminHref: "/admin/midias",
    action: "link" as const,
    contentKind: null,
    how: "Envie fotos e vídeos no Acervo. O que estiver autorizado e ligado a conteúdo publicado entra no portal.",
  },
] as const;

export type SiteDestination = (typeof siteDestinations)[number];
