import { TRPCError } from "@trpc/server";
import { randomBytes } from "node:crypto";
import { invokeLLM } from "../_core/llm";
import { transcribeAudio } from "../_core/voiceTranscription";
import { and, desc, eq, gt, gte, inArray, isNotNull, isNull, lte } from "drizzle-orm";
import { z } from "zod";
import { communityCareRequests, communityEvents, institutions, institutionVisibilitySubscriptions, mediaAssets, oralMemories, partners, taxonomies, users } from "../../drizzle/schema";
import { getDb } from "../db";
import { activeCommercialPolicy, createPayoutNotification } from "../financialGovernance";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";
import { publishEditorialEvent } from "../editorialEvents";
import { assertPartnerScope } from "../partnerScope";
import { decideCommunityHouseDirectory } from "@shared/territorialVisibility";

const recordStatuses = ["Rascunho", "Em revisão", "Publicada", "Arquivada"] as const;
const consentStatuses = ["Pendente", "Autorizado", "Retirado"] as const;
const accessLevels = ["Público", "Comunitário", "Pesquisa mediante análise", "Preservação restrita"] as const;
const careStatuses = ["Recebida", "Em acolhimento", "Encaminhada", "Arquivada"] as const;
const staffRoles = ["administrador", "administrador principal"] as const;
const institutionTypes = ["Casa de tradição", "Ilê/Terreiro", "Comunidade", "Coletivo", "Iniciativa", "Centro cultural", "Liderança religiosa", "Outro"] as const;
const visibilityPlans = ["Piloto solidário", "Visibilidade institucional", "Perfil parceiro"] as const;
const visibilityStatuses = ["Rascunho", "Aguardando confirmação", "Ativa", "Expirada", "Cancelada"] as const;
const isPrincipal = (role: string) => role === "administrador principal";
export const canAccessCommunityRecord = (role: string, userId: number, managedByUserId: number | null) => isPrincipal(role) || userId === managedByUserId;
function requireStaff(role: string) { if (!staffRoles.includes(role as typeof staffRoles[number])) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso comunitário não autorizado." }); }
async function requireDb() { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco de dados indisponível." }); return db; }
function requireAccess(role: string, userId: number, managedByUserId: number | null | undefined) { if (!canAccessCommunityRecord(role, userId, managedByUserId ?? null)) throw new TRPCError({ code: "FORBIDDEN", message: "Este registro pertence a outra carteira." }); }
async function requireCommunityPartnerScope(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, actor: { id: number; role: string }, partnerId: number | null | undefined, territoryId: number | null | undefined, label: string) {
  if (!partnerId) return;
  try { await assertPartnerScope({ db, actor, partnerId, territoryIds: territoryId ? [territoryId] : [], resourceLabel: label, requirePartner: true }); }
  catch (error) { throw new TRPCError({ code: "FORBIDDEN", message: error instanceof Error ? error.message : "Você não possui escopo territorial para este registro." }); }
}
async function assertEligibleCommunityMedia(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, mediaId: number, expectedType?: "foto" | "vídeo", requiresPublicationAllowed = false) {
  const media = (await db.select().from(mediaAssets).where(eq(mediaAssets.id, mediaId)).limit(1))[0];
  if (!media || media.state !== "Ativo" || media.deletedAt || (expectedType && media.mediaType !== expectedType) || (requiresPublicationAllowed && !media.publicationAllowed)) throw new TRPCError({ code: "BAD_REQUEST", message: requiresPublicationAllowed ? "A publicação exige mídia ativa, autorizada e fora da lixeira." : expectedType === "vídeo" ? "A memória precisa vincular um vídeo ativo e fora da lixeira." : "A mídia precisa estar ativa e fora da lixeira antes do vínculo comunitário." });
}
function money(value: number) { return (Math.round(value * 100) / 100).toFixed(2); }
function revenueSplit(netAmount: number, capturedByUserId: number | null, policy?: { ojuPercent: string; developmentPercent: string; captorPercent: string; executorPercent: string } | null) {
  if (!policy) throw new TRPCError({ code: "BAD_REQUEST", message: "Ative uma política de visibilidade institucional antes de registrar esta captação. Não há percentual padrão no código." });
  const ojuPercent = Number(policy.ojuPercent);
  const developmentPercent = Number(policy.developmentPercent);
  const captorPercent = Number(policy.captorPercent);
  const executorPercent = Number(policy.executorPercent);
  if (Math.abs(ojuPercent + developmentPercent + captorPercent + executorPercent - 100) > .001 || executorPercent !== 0) throw new TRPCError({ code: "BAD_REQUEST", message: "A política de visibilidade deve totalizar 100% e não pode incluir parcela de executor." });
  const cents = Math.round(netAmount * 100);
  const oju = Math.round(cents * ojuPercent / 100);
  const development = Math.round(cents * developmentPercent / 100);
  const captor = capturedByUserId ? Math.round(cents * captorPercent / 100) : 0;
  const reserve = cents - oju - development - captor;
  return { ojuAmount: money(oju / 100), developmentAmount: money(development / 100), captorAmount: money(captor / 100), reserveAmount: money(reserve / 100) };
}
function isVisibilityActive(status: string, startsAt: Date, expiresAt: Date, now = new Date()) { return status === "Ativa" && startsAt <= now && expiresAt > now; }
async function expirePastInstitutionVisibilities() { const db = await requireDb(); await db.update(institutionVisibilitySubscriptions).set({ status: "Expirada" }).where(and(eq(institutionVisibilitySubscriptions.status, "Ativa"), lte(institutionVisibilitySubscriptions.expiresAt, new Date()))); }
const institutionInput = z.object({ name: z.string().min(2).max(240), slug: z.string().min(2).max(260), institutionType: z.enum(institutionTypes), profileLabel: z.string().max(180).nullable().optional(), referenceName: z.string().max(240).nullable().optional(), referenceRole: z.string().max(180).nullable().optional(), description: z.string().max(10000).nullable().optional(), territoryId: z.number().int().positive().nullable().optional(), partnerId: z.number().int().positive().nullable().optional(), locationText: z.string().max(280).nullable().optional(), locationVisibility: z.enum(["Não divulgar", "Aproximada", "Pública"]), contactText: z.string().max(320).nullable().optional(), contactVisibility: z.enum(["Não divulgar", "Contato institucional"]), primaryMediaId: z.number().int().positive().nullable().optional(), status: z.enum(recordStatuses).optional(), consentStatus: z.enum(consentStatuses).optional(), consentNote: z.string().max(5000).nullable().optional() });
const institutionInputWithCoordinates = institutionInput.extend({ directoryScope: z.enum(["Institucional", "Serviço comunitário"]).optional(), serviceCategory: z.string().max(180).nullable().optional(), serviceKeywords: z.string().max(5000).nullable().optional(), neighborhoodText: z.string().max(180).nullable().optional(), latitude: z.string().regex(/^-?\d{1,2}(\.\d{1,7})?$/).nullable().optional(), longitude: z.string().regex(/^-?\d{1,3}(\.\d{1,7})?$/).nullable().optional() });
const visibilityInput = z.object({ institutionId: z.number().int().positive(), plan: z.enum(visibilityPlans), startsAt: z.date(), expiresAt: z.date(), grossAmount: z.coerce.number().positive(), netAmount: z.coerce.number().positive(), paymentReference: z.string().max(280).nullable().optional(), capturedByUserId: z.number().int().positive().nullable().optional() });
const eventInput = z.object({ title: z.string().min(2).max(280), slug: z.string().min(2).max(320), description: z.string().max(10000).nullable().optional(), institutionId: z.number().int().positive().nullable().optional(), territoryId: z.number().int().positive().nullable().optional(), partnerId: z.number().int().positive().nullable().optional(), startsAt: z.date(), endsAt: z.date().nullable().optional(), locationText: z.string().max(280).nullable().optional(), locationVisibility: z.enum(["Não divulgar", "Aproximada", "Pública"]), coverMediaId: z.number().int().positive().nullable().optional(), publicationId: z.number().int().positive().nullable().optional(), status: z.enum(recordStatuses).optional(), consentStatus: z.enum(consentStatuses).optional(), consentNote: z.string().max(5000).nullable().optional() });
const memoryInput = z.object({ title: z.string().min(2).max(280), slug: z.string().min(2).max(320), summary: z.string().max(5000).nullable().optional(), narrative: z.string().max(30000).nullable().optional(), theme: z.string().max(180).nullable().optional(), speakerName: z.string().max(240).nullable().optional(), speakerNameVisibility: z.enum(["Nome", "Pseudônimo", "Não divulgar"]), institutionId: z.number().int().positive().nullable().optional(), territoryId: z.number().int().positive().nullable().optional(), partnerId: z.number().int().positive().nullable().optional(), videoMediaId: z.number().int().positive().nullable().optional(), audioUrl: z.string().max(2000).nullable().optional(), audioStorageKey: z.string().max(512).nullable().optional(), accessLevel: z.enum(accessLevels), status: z.enum(recordStatuses).optional(), consentStatus: z.enum(consentStatuses).optional(), consentNote: z.string().max(5000).nullable().optional() });

export const communityRouter = router({
  publicDirectory: publicProcedure.query(async () => {
    await expirePastInstitutionVisibilities();
    const db = await requireDb();
    const now = new Date();
    const [rows, subscriptions] = await Promise.all([
      db.select().from(institutions).where(and(eq(institutions.status, "Publicada"), eq(institutions.consentStatus, "Autorizado"), isNull(institutions.deletedAt))).orderBy(desc(institutions.updatedAt)),
      db.select().from(institutionVisibilitySubscriptions).where(and(eq(institutionVisibilitySubscriptions.status, "Ativa"), lte(institutionVisibilitySubscriptions.startsAt, now), gt(institutionVisibilitySubscriptions.expiresAt, now))).orderBy(desc(institutionVisibilitySubscriptions.expiresAt)),
    ]);
    const byInstitution = new Map<number, typeof subscriptions[number]>();
    subscriptions.forEach(item => { if (!byInstitution.has(item.institutionId)) byInstitution.set(item.institutionId, item); });
    const primaryMediaIds = Array.from(new Set(rows.map(row => row.primaryMediaId).filter((id): id is number => Boolean(id))));
    const partnerIds = Array.from(new Set(rows.map(row => row.partnerId).filter((id): id is number => Boolean(id))));
    const territoryIds = Array.from(new Set(rows.map(row => row.territoryId).filter((id): id is number => Boolean(id))));
    const [media, visiblePartners, territoryRows] = await Promise.all([
      primaryMediaIds.length ? db.select().from(mediaAssets).where(and(inArray(mediaAssets.id, primaryMediaIds), eq(mediaAssets.publicationAllowed, true), eq(mediaAssets.state, "Ativo"), isNull(mediaAssets.deletedAt))) : Promise.resolve([]),
      partnerIds.length ? db.select({ id: partners.id, displayName: partners.displayName, slug: partners.slug, logoMediaId: partners.logoMediaId, instagramHandle: partners.instagramHandle }).from(partners).where(and(inArray(partners.id, partnerIds), eq(partners.status, "Ativo"), eq(partners.publicVisibility, true))) : Promise.resolve([]),
      territoryIds.length ? db.select({ id: taxonomies.id, name: taxonomies.name }).from(taxonomies).where(inArray(taxonomies.id, territoryIds)) : Promise.resolve([]),
    ]);
    const mediaById = new Map(media.map(item => [item.id, item]));
    const partnerById = new Map(visiblePartners.map(item => [item.id, item]));
    const territoryById = new Map(territoryRows.map(item => [item.id, item.name]));
    return rows.filter(row => decideCommunityHouseDirectory({
      status: row.status,
      consentStatus: row.consentStatus,
      deletedAt: row.deletedAt,
      directoryScope: row.directoryScope,
      hasActiveInstitutionalVisibilityPlan: byInstitution.has(row.id),
    }).allowed).map(row => {
      const visibility = byInstitution.get(row.id);
      const showLocation = row.locationVisibility !== "Não divulgar";
      const primaryMedia = row.primaryMediaId ? mediaById.get(row.primaryMediaId) : null;
      const partner = row.partnerId ? partnerById.get(row.partnerId) : null;
      return { id: row.id, name: row.name, slug: row.slug, institutionType: row.institutionType, profileLabel: row.profileLabel, directoryScope: row.directoryScope, serviceCategory: row.serviceCategory, serviceKeywords: row.serviceKeywords, neighborhoodText: showLocation ? row.neighborhoodText : null, description: row.description, territoryId: row.territoryId, territoryName: row.territoryId ? territoryById.get(row.territoryId) || null : null, locationText: showLocation ? row.locationText : null, locationVisibility: row.locationVisibility, contactText: row.contactVisibility === "Contato institucional" ? row.contactText : null, latitude: row.locationVisibility === "Pública" && row.latitude !== null ? Number(row.latitude) : null, longitude: row.locationVisibility === "Pública" && row.longitude !== null ? Number(row.longitude) : null, primaryMedia: primaryMedia ? { id: primaryMedia.id, assetUrl: primaryMedia.assetUrl, mediaType: primaryMedia.mediaType, credit: primaryMedia.credit } : null, partner: partner ? { displayName: partner.displayName, slug: partner.slug, instagramHandle: partner.instagramHandle || null } : null, visibilityPlan: visibility?.plan ?? null, visibilityExpiresAt: visibility?.expiresAt ?? null };
    });
  }),
  publicInstitutions: publicProcedure.query(async () => { await expirePastInstitutionVisibilities(); const db = await requireDb(); const now = new Date(); const rows = await db.select().from(institutions).where(and(eq(institutions.status, "Publicada"), eq(institutions.consentStatus, "Autorizado"), isNull(institutions.deletedAt))).orderBy(desc(institutions.updatedAt)); const subscriptions = await db.select().from(institutionVisibilitySubscriptions).where(and(eq(institutionVisibilitySubscriptions.status, "Ativa"), lte(institutionVisibilitySubscriptions.startsAt, now), gt(institutionVisibilitySubscriptions.expiresAt, now))).orderBy(desc(institutionVisibilitySubscriptions.expiresAt)); const byInstitution = new Map<number, typeof subscriptions[number]>(); subscriptions.forEach(item => { if (!byInstitution.has(item.institutionId)) byInstitution.set(item.institutionId, item); }); return rows.map(row => { const visibility = byInstitution.get(row.id); return { id: row.id, name: row.name, slug: row.slug, institutionType: row.institutionType, profileLabel: row.profileLabel, referenceName: row.referenceName, referenceRole: row.referenceRole, description: row.description, territoryId: row.territoryId, locationText: row.locationVisibility === "Não divulgar" ? null : row.locationText, locationVisibility: row.locationVisibility, contactText: row.contactVisibility === "Contato institucional" ? row.contactText : null, primaryMediaId: row.primaryMediaId, visibilityPlan: visibility?.plan ?? null, visibilityExpiresAt: visibility?.expiresAt ?? null }; }).sort((a, b) => Number(Boolean(b.visibilityPlan)) - Number(Boolean(a.visibilityPlan))); }),
  publicInstitutionMap: publicProcedure.query(async () => { const db = await requireDb(); const rows = await db.select().from(institutions).where(and(eq(institutions.status, "Publicada"), eq(institutions.consentStatus, "Autorizado"), isNull(institutions.deletedAt), eq(institutions.locationVisibility, "Pública"), isNotNull(institutions.latitude), isNotNull(institutions.longitude))).orderBy(desc(institutions.updatedAt)); return rows.map(row => ({ id: row.id, name: row.name, institutionType: row.institutionType, territoryId: row.territoryId, description: row.description, locationText: row.locationText, latitude: Number(row.latitude), longitude: Number(row.longitude) })); }),
  publicTerritories: publicProcedure.query(async () => { const db = await requireDb(); return db.select({ id: taxonomies.id, name: taxonomies.name }).from(taxonomies).where(eq(taxonomies.dimension, "Território")).orderBy(taxonomies.name); }),
  publicEvents: publicProcedure.query(async () => { const db = await requireDb(); const rows = await db.select().from(communityEvents).where(and(eq(communityEvents.status, "Publicada"), eq(communityEvents.consentStatus, "Autorizado"), isNull(communityEvents.deletedAt), gte(communityEvents.startsAt, new Date()))).orderBy(communityEvents.startsAt); const coverIds = Array.from(new Set(rows.map(row => row.coverMediaId).filter((id): id is number => Boolean(id)))); const media = coverIds.length ? await db.select().from(mediaAssets).where(and(inArray(mediaAssets.id, coverIds), eq(mediaAssets.publicationAllowed, true), eq(mediaAssets.state, "Ativo"), isNull(mediaAssets.deletedAt))) : []; const byId = new Map(media.map(item => [item.id, item])); return rows.map(row => { const cover = row.coverMediaId ? byId.get(row.coverMediaId) : null; return { id: row.id, title: row.title, slug: row.slug, description: row.description, institutionId: row.institutionId, territoryId: row.territoryId, startsAt: row.startsAt, endsAt: row.endsAt, locationText: row.locationVisibility === "Não divulgar" ? null : row.locationText, locationVisibility: row.locationVisibility, coverMedia: cover ? { id: cover.id, assetUrl: cover.assetUrl, mediaType: cover.mediaType, credit: cover.credit } : null, publicationId: row.publicationId }; }); }),
  publicMemories: publicProcedure.input(z.object({ query: z.string().max(180).optional(), theme: z.string().max(180).optional(), territoryId: z.number().int().positive().optional() }).optional()).query(async ({ input }) => { const db = await requireDb(); const rows = await db.select().from(oralMemories).where(and(eq(oralMemories.status, "Publicada"), eq(oralMemories.consentStatus, "Autorizado"), eq(oralMemories.accessLevel, "Público"), isNull(oralMemories.deletedAt))).orderBy(desc(oralMemories.updatedAt)); const videoIds = Array.from(new Set(rows.map(row => row.videoMediaId).filter((id): id is number => Boolean(id)))); const media = videoIds.length ? await db.select().from(mediaAssets).where(and(inArray(mediaAssets.id, videoIds), eq(mediaAssets.publicationAllowed, true), eq(mediaAssets.state, "Ativo"), isNull(mediaAssets.deletedAt))) : []; const byId = new Map(media.map(item => [item.id, item])); const query = input?.query?.trim().toLocaleLowerCase("pt-BR"); const theme = input?.theme?.trim().toLocaleLowerCase("pt-BR"); return rows.filter(row => (!input?.territoryId || row.territoryId === input.territoryId) && (!theme || row.theme?.toLocaleLowerCase("pt-BR").includes(theme)) && (!query || [row.title, row.summary, row.narrative, row.theme].filter(Boolean).join(" ").toLocaleLowerCase("pt-BR").includes(query))).map(row => { const video = row.videoMediaId ? byId.get(row.videoMediaId) : null; return { id: row.id, title: row.title, slug: row.slug, summary: row.summary, narrative: row.narrative, theme: row.theme, speakerName: row.speakerNameVisibility === "Não divulgar" ? null : row.speakerName, institutionId: row.institutionId, territoryId: row.territoryId, videoMedia: video ? { id: video.id, assetUrl: video.assetUrl, credit: video.credit } : null, audioUrl: row.audioUrl }; }); }),
  createCareRequest: publicProcedure.input(z.object({ requesterName: z.string().min(2).max(200), contact: z.string().min(5).max(320), territoryId: z.number().int().positive().optional(), requestType: z.enum(["Intolerância religiosa", "Risco ao acervo", "Registro documental", "Outro"]), details: z.string().min(10).max(10000) })).mutation(async ({ input }) => { const db = await requireDb(); const trackingCode = `AC-${randomBytes(9).toString("hex").toUpperCase()}`; const result = await db.insert(communityCareRequests).values({ ...input, trackingCode }); return { id: Number(result[0].insertId), trackingCode }; }),
  trackCareRequest: publicProcedure.input(z.object({ trackingCode: z.string().trim().min(8).max(48) })).query(async ({ input }) => { const db = await requireDb(); const request = (await db.select({ status: communityCareRequests.status, updatedAt: communityCareRequests.updatedAt }).from(communityCareRequests).where(eq(communityCareRequests.trackingCode, input.trackingCode.toUpperCase())).limit(1))[0]; if (!request) return null; return { status: request.status, updatedAt: request.updatedAt }; }),
  listInstitutions: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); const rows = isPrincipal(ctx.user.role) ? await db.select().from(institutions).orderBy(desc(institutions.updatedAt)) : await db.select().from(institutions).where(eq(institutions.managedByUserId, ctx.user.id)).orderBy(desc(institutions.updatedAt)); if (isPrincipal(ctx.user.role)) return rows; const scoped = await Promise.all(rows.map(async row => { try { await requireCommunityPartnerScope(db, ctx.user, row.partnerId, row.territoryId, "esta instituição"); return row; } catch { return null; } })); return scoped.filter((row): row is typeof rows[number] => Boolean(row)); }),
  createInstitution: protectedProcedure.input(institutionInputWithCoordinates).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); await requireCommunityPartnerScope(db, ctx.user, input.partnerId, input.territoryId, "esta instituição"); if (input.primaryMediaId) await assertEligibleCommunityMedia(db, input.primaryMediaId); const consentedAt = input.consentStatus === "Autorizado" ? new Date() : null; const result = await db.insert(institutions).values({ ...input, consentedAt, createdBy: ctx.user.id, managedByUserId: ctx.user.id }); publishEditorialEvent("community-institution-created", Number(result[0].insertId)); return { id: Number(result[0].insertId) }; }),
  updateInstitution: protectedProcedure.input(institutionInputWithCoordinates.partial().extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(institutions).where(eq(institutions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Instituição não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); await requireCommunityPartnerScope(db, ctx.user, current.partnerId, current.territoryId, "esta instituição"); if (input.partnerId !== undefined && input.partnerId !== current.partnerId && !isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Somente o Super Admin pode alterar o parceiro responsável." }); if (input.primaryMediaId) await assertEligibleCommunityMedia(db, input.primaryMediaId); const { id, consentStatus, ...values } = input; await db.update(institutions).set({ ...values, consentStatus, consentedAt: consentStatus === "Autorizado" ? (current.consentStatus === "Autorizado" ? current.consentedAt : new Date()) : consentStatus === "Retirado" ? null : current.consentedAt }).where(eq(institutions.id, id)); publishEditorialEvent("community-institution-updated", id); return { success: true }; }),
  assignInstitution: protectedProcedure.input(z.object({ id: z.number().int().positive(), managedByUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A distribuição é exclusiva do administrador principal." }); const db = await requireDb(); await db.update(institutions).set({ managedByUserId: input.managedByUserId }).where(eq(institutions.id, input.id)); return { success: true }; }),
  visibilityCaptors: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); if (!isPrincipal(ctx.user.role)) return db.select({ id: users.id, name: users.name, email: users.email }).from(users).where(eq(users.id, ctx.user.id)); return db.select({ id: users.id, name: users.name, email: users.email }).from(users).where(and(eq(users.adminAccess, true), inArray(users.role, staffRoles))); }),
  listInstitutionVisibilities: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); await expirePastInstitutionVisibilities(); const db = await requireDb(); const now = new Date(); const [rows, captors] = await Promise.all([isPrincipal(ctx.user.role) ? db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).orderBy(desc(institutionVisibilitySubscriptions.expiresAt)) : db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(eq(institutionVisibilitySubscriptions.capturedByUserId, ctx.user.id)).orderBy(desc(institutionVisibilitySubscriptions.expiresAt)), db.select({ id: users.id, name: users.name, email: users.email }).from(users)]); const captorNames = new Map(captors.map(item => [item.id, item.name || item.email || "Administrador"])); return rows.map(row => ({ ...row.subscription, institutionName: row.institution.name, institutionType: row.institution.institutionType, capturedByName: row.subscription.capturedByUserId ? captorNames.get(row.subscription.capturedByUserId) || "Administrador" : null, effectiveStatus: row.subscription.status, isCurrentlyVisible: isVisibilityActive(row.subscription.status, row.subscription.startsAt, row.subscription.expiresAt, now) })); }),
  createInstitutionVisibility: protectedProcedure.input(visibilityInput).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const institution = (await db.select().from(institutions).where(eq(institutions.id, input.institutionId)).limit(1))[0]; if (!institution) throw new TRPCError({ code: "NOT_FOUND", message: "Perfil comunitário não encontrado." }); requireAccess(ctx.user.role, ctx.user.id, institution.managedByUserId); if (input.expiresAt <= input.startsAt) throw new TRPCError({ code: "BAD_REQUEST", message: "A data de vencimento deve ser posterior ao início da vigência." }); const capturedByUserId = isPrincipal(ctx.user.role) ? (input.capturedByUserId ?? null) : ctx.user.id; if (capturedByUserId) { const captor = (await db.select({ id: users.id }).from(users).where(and(eq(users.id, capturedByUserId), eq(users.adminAccess, true), inArray(users.role, staffRoles))).limit(1))[0]; if (!captor) throw new TRPCError({ code: "BAD_REQUEST", message: "O administrador captador precisa ter acesso administrativo ativo." }); } const policy = await activeCommercialPolicy(db, "Visibilidade institucional"); const split = revenueSplit(input.netAmount, capturedByUserId, policy); const { capturedByUserId: _requestedCaptor, ...visibility } = input; const result = await db.insert(institutionVisibilitySubscriptions).values({ ...visibility, grossAmount: money(input.grossAmount), netAmount: money(input.netAmount), ...split, capturedByUserId, commercialPolicyId: policy?.id ?? null, commercialPolicyVersion: policy?.version ?? null, status: "Aguardando confirmação", createdBy: ctx.user.id }); return { id: Number(result[0].insertId) }; }),
  confirmInstitutionVisibility: protectedProcedure.input(z.object({ id: z.number().int().positive(), paymentReference: z.string().max(280).nullable().optional() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(eq(institutionVisibilitySubscriptions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Visibilidade institucional não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.institution.managedByUserId); await db.update(institutionVisibilitySubscriptions).set({ status: "Ativa", paidAt: new Date(), paymentReference: input.paymentReference ?? current.subscription.paymentReference }).where(eq(institutionVisibilitySubscriptions.id, input.id)); return { success: true }; }),
  cancelInstitutionVisibility: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(eq(institutionVisibilitySubscriptions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Visibilidade institucional não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.institution.managedByUserId); await db.update(institutionVisibilitySubscriptions).set({ status: "Cancelada" }).where(eq(institutionVisibilitySubscriptions.id, input.id)); return { success: true }; }),
  updateInstitutionVisibilityPayout: protectedProcedure.input(z.object({ id: z.number().int().positive(), captorPayoutStatus: z.enum(["Pendente", "Parcial", "Pago"]) })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A confirmação de repasse é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(eq(institutionVisibilitySubscriptions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Visibilidade institucional não encontrada." }); await db.update(institutionVisibilitySubscriptions).set({ captorPayoutStatus: input.captorPayoutStatus }).where(eq(institutionVisibilitySubscriptions.id, input.id)); if (input.captorPayoutStatus === "Pago" && current.subscription.captorPayoutStatus !== "Pago" && current.subscription.capturedByUserId) await createPayoutNotification(db, { recipientUserId: current.subscription.capturedByUserId, sourceType: "Visibilidade institucional", sourceId: current.subscription.id, title: "Repasse de captação concluído", message: `O repasse da vigência institucional “${current.institution.name}” foi marcado como pago pelo Super Admin.`, createdByUserId: ctx.user.id }); return { success: true }; }),
  visibilityRevenueSummary: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); await expirePastInstitutionVisibilities(); const db = await requireDb(); const now = new Date(); const active = and(eq(institutionVisibilitySubscriptions.status, "Ativa"), lte(institutionVisibilitySubscriptions.startsAt, now), gt(institutionVisibilitySubscriptions.expiresAt, now)); const rows = isPrincipal(ctx.user.role) ? await db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(active) : await db.select({ subscription: institutionVisibilitySubscriptions, institution: institutions }).from(institutionVisibilitySubscriptions).innerJoin(institutions, eq(institutionVisibilitySubscriptions.institutionId, institutions.id)).where(and(active, eq(institutionVisibilitySubscriptions.capturedByUserId, ctx.user.id))); const total = rows.reduce((sum, row) => ({ net: sum.net + Number(row.subscription.netAmount), oju: sum.oju + Number(row.subscription.ojuAmount), development: sum.development + Number(row.subscription.developmentAmount), captor: sum.captor + Number(row.subscription.captorAmount), reserve: sum.reserve + Number(row.subscription.reserveAmount) }), { net: 0, oju: 0, development: 0, captor: 0, reserve: 0 }); return { count: rows.length, netAmount: money(total.net), ojuAmount: money(total.oju), developmentAmount: money(total.development), captorAmount: money(total.captor), reserveAmount: money(total.reserve) }; }),
  listEvents: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); const rows = isPrincipal(ctx.user.role) ? await db.select().from(communityEvents).orderBy(communityEvents.startsAt) : await db.select().from(communityEvents).where(eq(communityEvents.managedByUserId, ctx.user.id)).orderBy(communityEvents.startsAt); if (isPrincipal(ctx.user.role)) return rows; const scoped = await Promise.all(rows.map(async row => { try { await requireCommunityPartnerScope(db, ctx.user, row.partnerId, row.territoryId, "este evento"); return row; } catch { return null; } })); return scoped.filter((row): row is typeof rows[number] => Boolean(row)); }),
  createEvent: protectedProcedure.input(eventInput).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); await requireCommunityPartnerScope(db, ctx.user, input.partnerId, input.territoryId, "este evento"); if (input.coverMediaId) await assertEligibleCommunityMedia(db, input.coverMediaId); const result = await db.insert(communityEvents).values({ ...input, consentedAt: input.consentStatus === "Autorizado" ? new Date() : null, createdBy: ctx.user.id, managedByUserId: ctx.user.id }); publishEditorialEvent("community-event-created", Number(result[0].insertId)); return { id: Number(result[0].insertId) }; }),
  updateEvent: protectedProcedure.input(eventInput.partial().extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(communityEvents).where(eq(communityEvents.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Evento não encontrado." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); await requireCommunityPartnerScope(db, ctx.user, current.partnerId, current.territoryId, "este evento"); if (input.partnerId !== undefined && input.partnerId !== current.partnerId && !isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Somente o Super Admin pode alterar o parceiro responsável." }); if (input.coverMediaId) await assertEligibleCommunityMedia(db, input.coverMediaId); const { id, consentStatus, ...values } = input; await db.update(communityEvents).set({ ...values, consentStatus, consentedAt: consentStatus === "Autorizado" ? (current.consentStatus === "Autorizado" ? current.consentedAt : new Date()) : consentStatus === "Retirado" ? null : current.consentedAt }).where(eq(communityEvents.id, id)); publishEditorialEvent("community-event-updated", id); return { success: true }; }),
  assignEvent: protectedProcedure.input(z.object({ id: z.number().int().positive(), managedByUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A distribuição é exclusiva do administrador principal." }); const db = await requireDb(); await db.update(communityEvents).set({ managedByUserId: input.managedByUserId }).where(eq(communityEvents.id, input.id)); return { success: true }; }),
  listMemories: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); const rows = isPrincipal(ctx.user.role) ? await db.select().from(oralMemories).orderBy(desc(oralMemories.updatedAt)) : await db.select().from(oralMemories).where(eq(oralMemories.managedByUserId, ctx.user.id)).orderBy(desc(oralMemories.updatedAt)); if (isPrincipal(ctx.user.role)) return rows; const scoped = await Promise.all(rows.map(async row => { try { await requireCommunityPartnerScope(db, ctx.user, row.partnerId, row.territoryId, "esta memória oral"); return row; } catch { return null; } })); return scoped.filter((row): row is typeof rows[number] => Boolean(row)); }),
  createMemory: protectedProcedure.input(memoryInput).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); await requireCommunityPartnerScope(db, ctx.user, input.partnerId, input.territoryId, "esta memória oral"); if (input.videoMediaId) await assertEligibleCommunityMedia(db, input.videoMediaId, "vídeo"); const result = await db.insert(oralMemories).values({ ...input, consentedAt: input.consentStatus === "Autorizado" ? new Date() : null, createdBy: ctx.user.id, managedByUserId: ctx.user.id }); publishEditorialEvent("community-memory-created", Number(result[0].insertId)); return { id: Number(result[0].insertId) }; }),
  createMemoryWithConsent: protectedProcedure.input(memoryInput.extend({ consentAccepted: z.literal(true), consentNote: z.string().min(12).max(5000) })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); if (input.consentStatus !== "Autorizado") throw new TRPCError({ code: "BAD_REQUEST", message: "A memória oral precisa de consentimento autorizado antes do envio." }); const db = await requireDb(); await requireCommunityPartnerScope(db, ctx.user, input.partnerId, input.territoryId, "esta memória oral"); if (input.videoMediaId) await assertEligibleCommunityMedia(db, input.videoMediaId, "vídeo"); const { consentAccepted: _consentAccepted, ...memory } = input; const result = await db.insert(oralMemories).values({ ...memory, consentedAt: new Date(), createdBy: ctx.user.id, managedByUserId: ctx.user.id }); publishEditorialEvent("community-memory-created", Number(result[0].insertId)); return { id: Number(result[0].insertId) }; }),
  generateMemoryAssistance: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const memory = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!memory) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, memory.managedByUserId); if (memory.consentStatus !== "Autorizado") throw new TRPCError({ code: "BAD_REQUEST", message: "A transcrição assistida exige consentimento autorizado." }); const video = memory.videoMediaId ? (await db.select().from(mediaAssets).where(eq(mediaAssets.id, memory.videoMediaId)).limit(1))[0] : null; const mediaUrl = memory.audioUrl || video?.assetUrl; if (!mediaUrl) throw new TRPCError({ code: "BAD_REQUEST", message: "Envie um áudio ou vídeo antes de solicitar a transcrição." }); const transcription = await transcribeAudio({ audioUrl: mediaUrl, language: "pt", prompt: "Transcreva em português brasileiro, preservando nomes próprios, referências culturais e pausas relevantes sem inventar conteúdo." }); if ("error" in transcription) throw new TRPCError({ code: "BAD_REQUEST", message: transcription.error }); const completion = await invokeLLM({ model: "gpt-5-mini", messages: [{ role: "system", content: "Você resume transcrições documentais em português brasileiro. Não invente fatos, não revele informações não presentes e escreva um resumo neutro de no máximo 110 palavras, para revisão editorial humana." }, { role: "user", content: `Título: ${memory.title}\nTema: ${memory.theme || "não informado"}\n\nTranscrição:\n${transcription.text}` }] }); const raw = completion.choices[0]?.message.content; const generatedSummary = typeof raw === "string" ? raw.trim() : ""; await db.update(oralMemories).set({ generatedTranscript: transcription.text, generatedSummary: generatedSummary || null, aiProcessedAt: new Date() }).where(eq(oralMemories.id, memory.id)); return { transcript: transcription.text, summary: generatedSummary }; }),
  reviewMemoryAssistance: protectedProcedure.input(z.object({ id: z.number().int().positive(), generatedTranscript: z.string().max(30000).nullable(), generatedSummary: z.string().max(5000).nullable() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const memory = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!memory) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, memory.managedByUserId); await requireCommunityPartnerScope(db, ctx.user, memory.partnerId, memory.territoryId, "esta memória oral"); await db.update(oralMemories).set({ generatedTranscript: input.generatedTranscript, generatedSummary: input.generatedSummary, aiReviewedAt: new Date(), aiReviewedBy: ctx.user.id }).where(eq(oralMemories.id, memory.id)); return { success: true }; }),
  updateMemory: protectedProcedure.input(memoryInput.partial().extend({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); await requireCommunityPartnerScope(db, ctx.user, current.partnerId, current.territoryId, "esta memória oral"); if (input.partnerId !== undefined && input.partnerId !== current.partnerId && !isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Somente o Super Admin pode alterar o parceiro responsável." }); if (input.videoMediaId) await assertEligibleCommunityMedia(db, input.videoMediaId, "vídeo"); const { id, consentStatus, ...values } = input; await db.update(oralMemories).set({ ...values, consentStatus, consentedAt: consentStatus === "Autorizado" ? (current.consentStatus === "Autorizado" ? current.consentedAt : new Date()) : consentStatus === "Retirado" ? null : current.consentedAt }).where(eq(oralMemories.id, id)); publishEditorialEvent("community-memory-updated", id); return { success: true }; }),
  assignMemory: protectedProcedure.input(z.object({ id: z.number().int().positive(), managedByUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A distribuição é exclusiva do administrador principal." }); const db = await requireDb(); await db.update(oralMemories).set({ managedByUserId: input.managedByUserId }).where(eq(oralMemories.id, input.id)); return { success: true }; }),
  setInstitutionStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(recordStatuses) })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(institutions).where(eq(institutions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Instituição não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); if (current.deletedAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Restaure o perfil antes de alterar sua etapa." }); if (input.status === "Publicada" && current.consentStatus !== "Autorizado") throw new TRPCError({ code: "BAD_REQUEST", message: "A publicação exige consentimento autorizado." }); if (input.status === "Publicada" && current.primaryMediaId) await assertEligibleCommunityMedia(db, current.primaryMediaId, undefined, true); await db.update(institutions).set({ status: input.status }).where(eq(institutions.id, input.id)); publishEditorialEvent("community-institution-status", input.id); return { success: true }; }),
  trashInstitution: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().trim().min(3).max(5000) })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A lixeira comunitária é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(institutions).where(eq(institutions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Instituição não encontrada." }); if (current.deletedAt) return { success: true }; await db.update(institutions).set({ status: "Arquivada", deletedAt: new Date(), deletedBy: ctx.user.id, deletionNote: input.note }).where(eq(institutions.id, input.id)); publishEditorialEvent("community-institution-trashed", input.id); return { success: true }; }),
  restoreInstitution: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A restauração é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(institutions).where(eq(institutions.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Instituição não encontrada." }); await db.update(institutions).set({ status: "Rascunho", deletedAt: null, deletedBy: null, deletionNote: null }).where(eq(institutions.id, input.id)); publishEditorialEvent("community-institution-restored", input.id); return { success: true }; }),
  setEventStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(recordStatuses) })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(communityEvents).where(eq(communityEvents.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Evento não encontrado." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); if (current.deletedAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Restaure o evento antes de alterar sua etapa." }); if (input.status === "Publicada" && current.consentStatus !== "Autorizado") throw new TRPCError({ code: "BAD_REQUEST", message: "A publicação exige consentimento autorizado." }); if (input.status === "Publicada" && current.coverMediaId) await assertEligibleCommunityMedia(db, current.coverMediaId, undefined, true); await db.update(communityEvents).set({ status: input.status }).where(eq(communityEvents.id, input.id)); publishEditorialEvent("community-event-status", input.id); return { success: true }; }),
  trashEvent: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().trim().min(3).max(5000) })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A lixeira comunitária é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(communityEvents).where(eq(communityEvents.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Evento não encontrado." }); if (current.deletedAt) return { success: true }; await db.update(communityEvents).set({ status: "Arquivada", deletedAt: new Date(), deletedBy: ctx.user.id, deletionNote: input.note }).where(eq(communityEvents.id, input.id)); publishEditorialEvent("community-event-trashed", input.id); return { success: true }; }),
  restoreEvent: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A restauração é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(communityEvents).where(eq(communityEvents.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Evento não encontrado." }); await db.update(communityEvents).set({ status: "Rascunho", deletedAt: null, deletedBy: null, deletionNote: null }).where(eq(communityEvents.id, input.id)); publishEditorialEvent("community-event-restored", input.id); return { success: true }; }),
  setMemoryStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(recordStatuses) })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); if (current.deletedAt) throw new TRPCError({ code: "BAD_REQUEST", message: "Restaure a memória antes de alterar sua etapa." }); if (input.status === "Publicada" && current.consentStatus !== "Autorizado") throw new TRPCError({ code: "BAD_REQUEST", message: "A publicação exige consentimento autorizado." }); if (input.status === "Publicada" && current.videoMediaId) await assertEligibleCommunityMedia(db, current.videoMediaId, "vídeo", true); await db.update(oralMemories).set({ status: input.status }).where(eq(oralMemories.id, input.id)); publishEditorialEvent("community-memory-status", input.id); return { success: true }; }),
  trashMemory: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().trim().min(3).max(5000) })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A lixeira comunitária é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); if (current.deletedAt) return { success: true }; await db.update(oralMemories).set({ status: "Arquivada", deletedAt: new Date(), deletedBy: ctx.user.id, deletionNote: input.note }).where(eq(oralMemories.id, input.id)); publishEditorialEvent("community-memory-trashed", input.id); return { success: true }; }),
  restoreMemory: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A restauração é exclusiva do administrador principal." }); const db = await requireDb(); const current = (await db.select().from(oralMemories).where(eq(oralMemories.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Memória não encontrada." }); await db.update(oralMemories).set({ status: "Rascunho", deletedAt: null, deletedBy: null, deletionNote: null }).where(eq(oralMemories.id, input.id)); publishEditorialEvent("community-memory-restored", input.id); return { success: true }; }),
  listCareRequests: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); return isPrincipal(ctx.user.role) ? db.select().from(communityCareRequests).orderBy(desc(communityCareRequests.createdAt)) : db.select().from(communityCareRequests).where(eq(communityCareRequests.managedByUserId, ctx.user.id)).orderBy(desc(communityCareRequests.createdAt)); }),
  claimCareRequest: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(communityCareRequests).where(eq(communityCareRequests.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Solicitação não encontrada." }); if (!isPrincipal(ctx.user.role) && current.managedByUserId && current.managedByUserId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "Esta solicitação já pertence a outra carteira." }); await db.update(communityCareRequests).set({ managedByUserId: ctx.user.id, status: current.status === "Recebida" ? "Em acolhimento" : current.status }).where(eq(communityCareRequests.id, input.id)); return { success: true }; }),
  assignCareRequest: protectedProcedure.input(z.object({ id: z.number().int().positive(), managedByUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "A distribuição é exclusiva do administrador principal." }); const db = await requireDb(); await db.update(communityCareRequests).set({ managedByUserId: input.managedByUserId }).where(eq(communityCareRequests.id, input.id)); return { success: true }; }),
  updateCareRequest: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(careStatuses).optional(), internalNote: z.string().max(10000).nullable().optional() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = (await db.select().from(communityCareRequests).where(eq(communityCareRequests.id, input.id)).limit(1))[0]; if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Solicitação não encontrada." }); requireAccess(ctx.user.role, ctx.user.id, current.managedByUserId); await db.update(communityCareRequests).set(input).where(eq(communityCareRequests.id, input.id)); return { success: true }; }),
});
