import { and, desc, eq, inArray } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { advertisements, commercialPayoutNotifications, commercialPolicies, commercialRefundPolicies, commercialRefundRequests, commercialRequests, commercialTransactions, institutionVisibilitySubscriptions, users } from "../../drizzle/schema";
import { createPayoutNotification, isPrincipalFinancial, money, payoutBreakdown, policyScopes, requireFinancialAccess, requireFinancialDb, requireFinancialPrincipal } from "../financialGovernance";
import { protectedProcedure, router } from "../_core/trpc";
import { recordAuditEvent } from "../partnerScope";

const payoutStatuses = ["Pendente", "Parcial", "Pago"] as const;
const policyStatuses = ["Rascunho", "Ativa", "Substituída", "Arquivada"] as const;
const policyInput = z.object({ label: z.string().min(3).max(240), scope: z.enum(policyScopes), effectiveAt: z.date(), ojuPercent: z.coerce.number().min(0).max(100), developmentPercent: z.coerce.number().min(0).max(100), captorPercent: z.coerce.number().min(0).max(100), executorPercent: z.coerce.number().min(0).max(100), notes: z.string().max(5000).nullable().optional() });
const refundPolicyInput = z.object({ requestWindowDays: z.number().int().min(1).max(365), maximumRefundPercent: z.coerce.number().gt(0).lt(100), retentionExplanation: z.string().trim().min(12).max(5000) });
const moneyInput = z.coerce.number().positive().max(99999999);

function validatePolicy(input: z.infer<typeof policyInput>) { if (Math.abs(input.ojuPercent + input.developmentPercent + input.captorPercent + input.executorPercent - 100) > .001) throw new Error("A distribuição da política deve totalizar 100%."); if (input.scope === "Anúncio" && (input.developmentPercent !== 0 || input.executorPercent !== 0)) throw new Error("A política de anúncio deve dividir somente entre Ojú e captação."); if (input.scope === "Visibilidade institucional" && input.executorPercent !== 0) throw new Error("A política de visibilidade institucional não pode incluir parcela de executor."); }
function asMoney(value: number) { return money(value).toFixed(2); }
async function secureFinancialRequest(db: Awaited<ReturnType<typeof requireFinancialDb>>, actor: { id: number; role: string }, requestId: number) {
  const request = (await db.select().from(commercialRequests).where(eq(commercialRequests.id, requestId)).limit(1))[0];
  if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "Contratação não encontrada." });
  if (!isPrincipalFinancial(actor.role) && request.managedByUserId !== actor.id) throw new TRPCError({ code: "FORBIDDEN", message: "Esta contratação pertence a outra carteira." });
  return request;
}

export const financialRouter = router({
  earnings: protectedProcedure.query(async ({ ctx }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); const [ads, visibilities, accounts] = await Promise.all([isPrincipalFinancial(ctx.user.role) ? db.select().from(advertisements).orderBy(desc(advertisements.createdAt)) : db.select().from(advertisements).where(eq(advertisements.capturedByUserId, ctx.user.id)).orderBy(desc(advertisements.createdAt)), isPrincipalFinancial(ctx.user.role) ? db.select().from(institutionVisibilitySubscriptions).where(inArray(institutionVisibilitySubscriptions.captorPayoutStatus, payoutStatuses)).orderBy(desc(institutionVisibilitySubscriptions.createdAt)) : db.select().from(institutionVisibilitySubscriptions).where(eq(institutionVisibilitySubscriptions.capturedByUserId, ctx.user.id)).orderBy(desc(institutionVisibilitySubscriptions.createdAt)), db.select({ id: users.id, name: users.name, email: users.email }).from(users)]); const names = new Map(accounts.map(account => [account.id, account.name || account.email || "Administrador"])); const items = [
    ...ads.map(ad => ({ id: ad.id, sourceType: "Anúncio" as const, title: ad.title, detail: ad.advertiserName, recipientUserId: ad.capturedByUserId, recipientName: names.get(ad.capturedByUserId) || "Administrador", amount: money(Number(ad.contractedAmount) * Number(ad.captorSharePercent) / 100), status: ad.payoutStatus, policyVersion: ad.commercialPolicyVersion, createdAt: ad.createdAt })),
    ...visibilities.filter(item => item.capturedByUserId).map(item => ({ id: item.id, sourceType: "Visibilidade institucional" as const, title: item.plan, detail: `Vigência institucional #${item.institutionId}`, recipientUserId: item.capturedByUserId!, recipientName: names.get(item.capturedByUserId!) || "Administrador", amount: money(Number(item.captorAmount)), status: item.captorPayoutStatus, policyVersion: item.commercialPolicyVersion, createdAt: item.createdAt })),
  ].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()); const summary = payoutBreakdown(items); const byAdministrator = Object.values(items.reduce<Record<number, { userId: number; name: string; expected: number; paid: number; partial: number; pending: number }>>((acc, item) => { const current = acc[item.recipientUserId] || { userId: item.recipientUserId, name: item.recipientName, expected: 0, paid: 0, partial: 0, pending: 0 }; current.expected += item.amount; if (item.status === "Pago") current.paid += item.amount; else if (item.status === "Parcial") current.partial += item.amount; else current.pending += item.amount; acc[item.recipientUserId] = current; return acc; }, {})); return { scope: isPrincipalFinancial(ctx.user.role) ? "consolidado" : "proprio", summary: Object.fromEntries(Object.entries(summary).map(([key, value]) => [key, money(value)])), byAdministrator: byAdministrator.map(item => ({ ...item, expected: money(item.expected), paid: money(item.paid), partial: money(item.partial), pending: money(item.pending) })), items: items.map(item => ({ ...item, amount: money(item.amount) })) }; }),
  listPolicies: protectedProcedure.query(async ({ ctx }) => { requireFinancialPrincipal(ctx.user.role); return (await requireFinancialDb()).select().from(commercialPolicies).orderBy(desc(commercialPolicies.createdAt)); }),
  createPolicy: protectedProcedure.input(policyInput).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); try { validatePolicy(input); } catch (error) { throw new Error(error instanceof Error ? error.message : "Política inválida."); } const db = await requireFinancialDb(); const latest = (await db.select().from(commercialPolicies).where(eq(commercialPolicies.scope, input.scope)).orderBy(desc(commercialPolicies.version)).limit(1))[0]; const result = await db.insert(commercialPolicies).values({ ...input, version: (latest?.version || 0) + 1, status: "Rascunho", ojuPercent: input.ojuPercent.toFixed(2), developmentPercent: input.developmentPercent.toFixed(2), captorPercent: input.captorPercent.toFixed(2), executorPercent: input.executorPercent.toFixed(2), notes: input.notes?.trim() || null, createdByUserId: ctx.user.id }); return { id: Number(result[0].insertId) }; }),
  activatePolicy: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const policy = (await db.select().from(commercialPolicies).where(eq(commercialPolicies.id, input.id)).limit(1))[0]; if (!policy) throw new Error("Política comercial não encontrada."); if (policy.status === "Arquivada") throw new Error("Uma política arquivada não pode ser ativada."); await db.update(commercialPolicies).set({ status: "Substituída" }).where(eq(commercialPolicies.scope, policy.scope)); await db.update(commercialPolicies).set({ status: "Ativa", activatedAt: new Date(), activatedByUserId: ctx.user.id }).where(eq(commercialPolicies.id, policy.id)); return { success: true }; }),
  archivePolicy: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); await db.update(commercialPolicies).set({ status: "Arquivada" }).where(eq(commercialPolicies.id, input.id)); return { success: true }; }),
  activePolicy: protectedProcedure.input(z.object({ scope: z.enum(policyScopes) })).query(async ({ ctx, input }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); return (await db.select().from(commercialPolicies).where(and(eq(commercialPolicies.scope, input.scope), eq(commercialPolicies.status, "Ativa"))).orderBy(desc(commercialPolicies.version)).limit(1))[0] ?? null; }),
  refundPolicies: protectedProcedure.query(async ({ ctx }) => { requireFinancialPrincipal(ctx.user.role); return (await requireFinancialDb()).select().from(commercialRefundPolicies).orderBy(desc(commercialRefundPolicies.version)); }),
  createRefundPolicy: protectedProcedure.input(refundPolicyInput).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const latest = (await db.select().from(commercialRefundPolicies).orderBy(desc(commercialRefundPolicies.version)).limit(1))[0]; const result = await db.insert(commercialRefundPolicies).values({ version: (latest?.version || 0) + 1, requestWindowDays: input.requestWindowDays, maximumRefundPercent: asMoney(input.maximumRefundPercent), retentionExplanation: input.retentionExplanation.trim(), createdByUserId: ctx.user.id }); return { id: Number(result[0].insertId) }; }),
  activateRefundPolicy: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const policy = (await db.select().from(commercialRefundPolicies).where(eq(commercialRefundPolicies.id, input.id)).limit(1))[0]; if (!policy) throw new TRPCError({ code: "NOT_FOUND", message: "Política de reembolso não encontrada." }); if (policy.status === "Arquivada") throw new TRPCError({ code: "BAD_REQUEST", message: "Uma política arquivada não pode ser ativada." }); await db.update(commercialRefundPolicies).set({ status: "Substituída" }).where(eq(commercialRefundPolicies.status, "Ativa")); await db.update(commercialRefundPolicies).set({ status: "Ativa", activatedAt: new Date(), activatedByUserId: ctx.user.id }).where(eq(commercialRefundPolicies.id, policy.id)); return { success: true }; }),
  recordCharge: protectedProcedure.input(z.object({ requestId: z.number().int().positive(), grossAmount: moneyInput, executorAmount: z.coerce.number().min(0), partnerGrossAmount: z.coerce.number().min(0), reason: z.string().trim().min(3).max(2000).optional() })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const request = await secureFinancialRequest(db, ctx.user, input.requestId); if (Math.abs(input.grossAmount - input.executorAmount - input.partnerGrossAmount) > .01) throw new TRPCError({ code: "BAD_REQUEST", message: "O valor bruto deve ser igual à parcela do executor somada à parcela bruta do parceiro." }); const partnerNet = money(input.partnerGrossAmount * .95); const ojuAmount = money(input.partnerGrossAmount - partnerNet); const result = await db.insert(commercialTransactions).values({ requestId: request.id, partnerId: request.partnerId, territoryId: request.territoryId, transactionType: "Cobrança", status: "Registrada", grossAmount: asMoney(input.grossAmount), executorAmount: asMoney(input.executorAmount), partnerGrossAmount: asMoney(input.partnerGrossAmount), partnerNetAmount: asMoney(partnerNet), ojuAmount: asMoney(ojuAmount), retainedCostsAmount: "0.00", reason: input.reason?.trim() || null, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await recordAuditEvent(db, { actorId: ctx.user.id, partnerId: request.partnerId, territoryId: request.territoryId, resourceType: "commercial-transaction", resourceId: id, action: "charge-recorded", nextState: { grossAmount: asMoney(input.grossAmount), executorAmount: asMoney(input.executorAmount), partnerGrossAmount: asMoney(input.partnerGrossAmount), partnerNetAmount: asMoney(partnerNet), ojuAmount: asMoney(ojuAmount) }, detail: "Cobrança registrada como lançamento imutável; 5% da parcela do parceiro foram destinados à operação Ojú." }); return { id, partnerNetAmount: asMoney(partnerNet), ojuAmount: asMoney(ojuAmount) }; }),
  transactionsForRequest: protectedProcedure.input(z.object({ requestId: z.number().int().positive() })).query(async ({ ctx, input }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); await secureFinancialRequest(db, ctx.user, input.requestId); return db.select().from(commercialTransactions).where(eq(commercialTransactions.requestId, input.requestId)).orderBy(desc(commercialTransactions.createdAt)); }),
  requestRefund: protectedProcedure.input(z.object({ requestId: z.number().int().positive(), originalTransactionId: z.number().int().positive(), requestedAmount: moneyInput, reason: z.string().trim().min(12).max(5000) })).mutation(async ({ ctx, input }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); const request = await secureFinancialRequest(db, ctx.user, input.requestId); const transaction = (await db.select().from(commercialTransactions).where(and(eq(commercialTransactions.id, input.originalTransactionId), eq(commercialTransactions.requestId, request.id), eq(commercialTransactions.transactionType, "Cobrança"))).limit(1))[0]; if (!transaction) throw new TRPCError({ code: "NOT_FOUND", message: "Cobrança original não encontrada." }); const policy = (await db.select().from(commercialRefundPolicies).where(eq(commercialRefundPolicies.status, "Ativa")).orderBy(desc(commercialRefundPolicies.version)).limit(1))[0]; if (!policy) throw new TRPCError({ code: "BAD_REQUEST", message: "O Super Admin precisa ativar uma política de reembolso antes de registrar solicitações." }); const deadline = new Date(transaction.createdAt); deadline.setUTCDate(deadline.getUTCDate() + policy.requestWindowDays); if (new Date() > deadline) throw new TRPCError({ code: "BAD_REQUEST", message: "O prazo desta política para solicitar reembolso já expirou." }); const cap = money(Number(transaction.grossAmount) * Number(policy.maximumRefundPercent) / 100); if (input.requestedAmount > cap) throw new TRPCError({ code: "BAD_REQUEST", message: `O valor solicitado excede o teto de ${policy.maximumRefundPercent}% definido pela política ativa.` }); const result = await db.insert(commercialRefundRequests).values({ requestId: request.id, originalTransactionId: transaction.id, refundPolicyId: policy.id, refundPolicyVersion: policy.version, requestedAmount: asMoney(input.requestedAmount), reason: input.reason.trim(), requestedByUserId: ctx.user.id }); const id = Number(result[0].insertId); await recordAuditEvent(db, { actorId: ctx.user.id, partnerId: request.partnerId, territoryId: request.territoryId, resourceType: "refund-request", resourceId: id, action: "refund-requested", nextState: { requestedAmount: asMoney(input.requestedAmount), policyVersion: policy.version }, detail: "Solicitação de reembolso parcial registrada dentro do prazo da política vigente." }); return { id, maximumEligibleAmount: asMoney(cap), deadline }; }),
  decideRefund: protectedProcedure.input(z.object({ id: z.number().int().positive(), approved: z.boolean(), approvedAmount: z.coerce.number().min(0).optional(), decisionNote: z.string().trim().min(3).max(5000) })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const refund = (await db.select().from(commercialRefundRequests).where(eq(commercialRefundRequests.id, input.id)).limit(1))[0]; if (!refund || refund.status !== "Solicitado") throw new TRPCError({ code: "BAD_REQUEST", message: "Esta solicitação não está disponível para decisão." }); const request = await secureFinancialRequest(db, ctx.user, refund.requestId); const original = (await db.select().from(commercialTransactions).where(eq(commercialTransactions.id, refund.originalTransactionId)).limit(1))[0]; const policy = (await db.select().from(commercialRefundPolicies).where(eq(commercialRefundPolicies.id, refund.refundPolicyId)).limit(1))[0]; if (!original || !policy) throw new TRPCError({ code: "BAD_REQUEST", message: "Não foi possível recuperar a cobrança ou a política original." }); const approvedAmount = input.approved ? input.approvedAmount ?? Number(refund.requestedAmount) : 0; const cap = money(Number(original.grossAmount) * Number(policy.maximumRefundPercent) / 100); if (input.approved && (approvedAmount <= 0 || approvedAmount > cap || approvedAmount >= Number(original.grossAmount))) throw new TRPCError({ code: "BAD_REQUEST", message: "O reembolso deve ser positivo, respeitar o teto vigente e nunca atingir 100% da cobrança." }); const now = new Date(); await db.update(commercialRefundRequests).set({ status: input.approved ? "Aprovado" : "Recusado", approvedAmount: input.approved ? asMoney(approvedAmount) : null, retainedCostsAmount: input.approved ? asMoney(Number(original.grossAmount) - approvedAmount) : null, decisionNote: input.decisionNote.trim(), decidedByUserId: ctx.user.id, decidedAt: now }).where(eq(commercialRefundRequests.id, refund.id)); await recordAuditEvent(db, { actorId: ctx.user.id, partnerId: request.partnerId, territoryId: request.territoryId, resourceType: "refund-request", resourceId: refund.id, action: input.approved ? "refund-approved" : "refund-rejected", previousState: { status: "Solicitado" }, nextState: { status: input.approved ? "Aprovado" : "Recusado", approvedAmount: input.approved ? asMoney(approvedAmount) : null }, detail: "Decisão de reembolso registrada pelo Super Admin; a cobrança original permanece imutável." }); return { success: true, retainedCostsAmount: input.approved ? asMoney(Number(original.grossAmount) - approvedAmount) : null }; }),
  compensateRefund: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().trim().min(3).max(5000).optional() })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); const db = await requireFinancialDb(); const refund = (await db.select().from(commercialRefundRequests).where(eq(commercialRefundRequests.id, input.id)).limit(1))[0]; if (!refund || refund.status !== "Aprovado" || !refund.approvedAmount) throw new TRPCError({ code: "BAD_REQUEST", message: "Somente um reembolso aprovado pode ser compensado." }); const request = await secureFinancialRequest(db, ctx.user, refund.requestId); const original = (await db.select().from(commercialTransactions).where(eq(commercialTransactions.id, refund.originalTransactionId)).limit(1))[0]; if (!original) throw new TRPCError({ code: "NOT_FOUND", message: "Cobrança original não encontrada." }); const result = await db.insert(commercialTransactions).values({ requestId: request.id, partnerId: request.partnerId, territoryId: request.territoryId, transactionType: "Reembolso", status: "Compensada", grossAmount: asMoney(-Number(refund.approvedAmount)), executorAmount: "0.00", partnerGrossAmount: "0.00", partnerNetAmount: "0.00", ojuAmount: "0.00", retainedCostsAmount: asMoney(Number(original.grossAmount) - Number(refund.approvedAmount)), refundPolicyId: refund.refundPolicyId, refundPolicyVersion: refund.refundPolicyVersion, originalTransactionId: original.id, reason: input.note?.trim() || refund.reason, createdByUserId: ctx.user.id }); const transactionId = Number(result[0].insertId); await db.update(commercialRefundRequests).set({ status: "Compensado", compensatedTransactionId: transactionId }).where(eq(commercialRefundRequests.id, refund.id)); await recordAuditEvent(db, { actorId: ctx.user.id, partnerId: request.partnerId, territoryId: request.territoryId, resourceType: "refund-request", resourceId: refund.id, action: "refund-compensated", nextState: { compensationTransactionId: transactionId, approvedAmount: refund.approvedAmount }, detail: "Lançamento compensatório criado sem apagar a cobrança original; os custos retidos permanecem registrados." }); return { transactionId }; }),
  notifications: protectedProcedure.query(async ({ ctx }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); const rows = isPrincipalFinancial(ctx.user.role) ? await db.select({ notification: commercialPayoutNotifications, recipientName: users.name, recipientEmail: users.email }).from(commercialPayoutNotifications).leftJoin(users, eq(commercialPayoutNotifications.recipientUserId, users.id)).orderBy(desc(commercialPayoutNotifications.createdAt)) : await db.select({ notification: commercialPayoutNotifications, recipientName: users.name, recipientEmail: users.email }).from(commercialPayoutNotifications).leftJoin(users, eq(commercialPayoutNotifications.recipientUserId, users.id)).where(eq(commercialPayoutNotifications.recipientUserId, ctx.user.id)).orderBy(desc(commercialPayoutNotifications.createdAt)); return rows.map(row => ({ ...row.notification, recipientName: row.recipientName || row.recipientEmail || "Administrador" })); }),
  markNotificationRead: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireFinancialAccess(ctx.user.role); const db = await requireFinancialDb(); const notification = (await db.select().from(commercialPayoutNotifications).where(eq(commercialPayoutNotifications.id, input.id)).limit(1))[0]; if (!notification) throw new Error("Aviso de repasse não encontrado."); if (!isPrincipalFinancial(ctx.user.role) && notification.recipientUserId !== ctx.user.id) throw new Error("Você não pode alterar o aviso de outra carteira."); await db.update(commercialPayoutNotifications).set({ readAt: new Date() }).where(eq(commercialPayoutNotifications.id, notification.id)); return { success: true }; }),
  notifyPayoutCompleted: protectedProcedure.input(z.object({ recipientUserId: z.number().int().positive(), sourceType: z.enum(["Anúncio", "Visibilidade institucional"]), sourceId: z.number().int().positive(), title: z.string().min(2).max(280), message: z.string().min(2).max(4000) })).mutation(async ({ ctx, input }) => { requireFinancialPrincipal(ctx.user.role); await createPayoutNotification(await requireFinancialDb(), { ...input, createdByUserId: ctx.user.id }); return { success: true }; }),
});
