import { TRPCError } from "@trpc/server";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { mediaAssets, revenueLeadActivities, revenueLeads } from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, publicProcedure, router } from "../_core/trpc";

const leadTypes = ["Apoio institucional", "Licenciamento de mídia", "Oficina"] as const;
const leadStatuses = ["Solicitação", "Em análise", "Conversa", "Proposta", "Acordo", "Concluído", "Arquivado"] as const;
const leadInput = z.object({ leadType: z.enum(leadTypes), contactName: z.string().min(2).max(200), organization: z.string().max(240).optional(), whatsapp: z.string().min(8).max(40), email: z.string().email().max(320).optional(), purpose: z.string().min(3).max(280), details: z.string().max(5000).optional(), publicationId: z.number().int().positive().optional(), taxonomyId: z.number().int().positive().optional(), mediaId: z.number().int().positive().optional(), licenseScope: z.string().max(4000).optional() });
const staffRoles = ["administrador", "administrador principal"] as const;
const isPrincipal = (role: string) => role === "administrador principal";
export const canAccessRevenueLead = (role: string, userId: number, managedByUserId: number | null) => isPrincipal(role) || userId === managedByUserId;
async function requireDb() { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Banco de dados indisponível." }); return db; }
function requireStaff(role: string) { if (!staffRoles.includes(role as typeof staffRoles[number])) throw new TRPCError({ code: "FORBIDDEN", message: "Acesso comercial não autorizado." }); }
function secureLead(role: string, userId: number, lead: typeof revenueLeads.$inferSelect | undefined) { if (!lead) throw new TRPCError({ code: "NOT_FOUND", message: "Registro não encontrado." }); if (!canAccessRevenueLead(role, userId, lead.managedByUserId)) throw new TRPCError({ code: "FORBIDDEN", message: "Você só pode acessar registros da sua carteira." }); return lead; }
async function activity(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, leadId: number, actorId: number | null, detail: string) { await db.insert(revenueLeadActivities).values({ leadId, actorId, detail }); }

export const revenueRouter = router({
  createPublic: publicProcedure.input(leadInput).mutation(async ({ input }) => { const db = await requireDb(); if (input.leadType === "Licenciamento de mídia") { if (!input.mediaId) throw new TRPCError({ code: "BAD_REQUEST", message: "Selecione a mídia que deseja licenciar." }); const media = (await db.select().from(mediaAssets).where(eq(mediaAssets.id, input.mediaId)).limit(1))[0]; if (!media || media.state !== "Ativo") throw new TRPCError({ code: "NOT_FOUND", message: "Mídia não disponível para solicitação." }); }
    const result = await db.insert(revenueLeads).values(input); const id = Number(result[0].insertId); await activity(db, id, null, `${input.leadType} recebido e aguardando análise da Ojú.`); return { id }; }),
  list: protectedProcedure.query(async ({ ctx }) => { requireStaff(ctx.user.role); const db = await requireDb(); return isPrincipal(ctx.user.role) ? db.select().from(revenueLeads).orderBy(desc(revenueLeads.createdAt)) : db.select().from(revenueLeads).where(eq(revenueLeads.managedByUserId, ctx.user.id)).orderBy(desc(revenueLeads.createdAt)); }),
  claim: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const lead = (await db.select().from(revenueLeads).where(eq(revenueLeads.id, input.id)).limit(1))[0]; if (!lead) throw new TRPCError({ code: "NOT_FOUND", message: "Registro não encontrado." }); if (!isPrincipal(ctx.user.role) && lead.managedByUserId && lead.managedByUserId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "Esta oportunidade já pertence a outra carteira." }); await db.update(revenueLeads).set({ managedByUserId: ctx.user.id, status: lead.status === "Solicitação" ? "Em análise" : lead.status }).where(eq(revenueLeads.id, input.id)); await activity(db, input.id, ctx.user.id, "Carteira assumida para análise comercial."); return { success: true }; }),
  assign: protectedProcedure.input(z.object({ id: z.number().int().positive(), managedByUserId: z.number().int().positive().nullable() })).mutation(async ({ ctx, input }) => { if (!isPrincipal(ctx.user.role)) throw new TRPCError({ code: "FORBIDDEN", message: "Apenas o administrador principal distribui carteiras." }); const db = await requireDb(); secureLead(ctx.user.role, ctx.user.id, (await db.select().from(revenueLeads).where(eq(revenueLeads.id, input.id)).limit(1))[0]); await db.update(revenueLeads).set({ managedByUserId: input.managedByUserId }).where(eq(revenueLeads.id, input.id)); await activity(db, input.id, ctx.user.id, input.managedByUserId ? "Carteira distribuída pelo administrador principal." : "Carteira liberada pelo administrador principal."); return { success: true }; }),
  update: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(leadStatuses).optional(), proposalSummary: z.string().max(5000).nullable().optional(), proposalAmount: z.number().positive().nullable().optional(), licenseScope: z.string().max(4000).nullable().optional() })).mutation(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); const current = secureLead(ctx.user.role, ctx.user.id, (await db.select().from(revenueLeads).where(eq(revenueLeads.id, input.id)).limit(1))[0]); const { id, proposalAmount, ...values } = input; await db.update(revenueLeads).set({ ...values, proposalAmount: proposalAmount === undefined || proposalAmount === null ? proposalAmount : proposalAmount.toFixed(2) }).where(eq(revenueLeads.id, id)); if (input.status && input.status !== current.status) await activity(db, id, ctx.user.id, `Etapa alterada de ${current.status} para ${input.status}.`); if (input.proposalSummary !== undefined || input.proposalAmount !== undefined) await activity(db, id, ctx.user.id, "Proposta comercial atualizada na carteira privada."); return { success: true }; }),
  activities: protectedProcedure.input(z.object({ leadId: z.number().int().positive() })).query(async ({ ctx, input }) => { requireStaff(ctx.user.role); const db = await requireDb(); secureLead(ctx.user.role, ctx.user.id, (await db.select().from(revenueLeads).where(eq(revenueLeads.id, input.leadId)).limit(1))[0]); return db.select().from(revenueLeadActivities).where(eq(revenueLeadActivities.leadId, input.leadId)).orderBy(desc(revenueLeadActivities.createdAt)); }),
  mediaEligibleForLicense: protectedProcedure.input(z.object({ mediaId: z.number().int().positive() })).query(async ({ input }) => { const db = await requireDb(); const media = (await db.select({ id: mediaAssets.id, mediaType: mediaAssets.mediaType, credit: mediaAssets.credit, authorization: mediaAssets.authorization, publicationAllowed: mediaAssets.publicationAllowed, state: mediaAssets.state, usageExpiresAt: mediaAssets.usageExpiresAt }).from(mediaAssets).where(eq(mediaAssets.id, input.mediaId)).limit(1))[0]; if (!media || media.state !== "Ativo") return { eligible: false, reason: "Mídia indisponível." }; if (media.usageExpiresAt && media.usageExpiresAt < new Date()) return { eligible: false, reason: "A permissão registrada para esta mídia expirou." }; return { eligible: true, media }; }),
});
