import { Search, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { PublicHeader } from "@/components/PublicHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

const labels = { "Recebida": "Pedido recebido", "Em acolhimento": "Em acolhimento", "Encaminhada": "Encaminhado", "Arquivada": "Concluído e arquivado" } as const;
export default function CareTracking() { const [code, setCode] = useState(""); const [submitted, setSubmitted] = useState(""); const tracking = trpc.community.trackCareRequest.useQuery({ trackingCode: submitted }, { enabled: submitted.length > 0 }); return <div className="public-page"><PublicHeader /><main className="container grid gap-12 pb-20 pt-16 lg:grid-cols-[.9fr_1.1fr]"><section><ShieldCheck className="h-8 w-8 text-oju-dende"/><p className="mt-8 text-[10px] font-bold uppercase tracking-[.16em] text-oju-dende">Acompanhamento reservado</p><h1 className="mt-5 max-w-xl font-serif text-6xl leading-[.94]">Acompanhe seu pedido sem expor sua história.</h1><p className="mt-7 max-w-xl text-base leading-7 text-oju-terra-suave">Use o protocolo recebido ao enviar a solicitação. Esta consulta mostra somente a etapa atual e a última atualização; não revela detalhes, contatos ou anotações internas.</p></section><section className="h-fit rounded border border-oju-terra/12 bg-oju-paz-claro p-6 sm:p-8"><form className="grid gap-4" onSubmit={event => { event.preventDefault(); setSubmitted(code.trim().toUpperCase()); }}><label className="grid gap-2 text-sm">Protocolo de acolhimento<Input required value={code} onChange={event => setCode(event.target.value)} placeholder="AC-XXXXXXXX" className="border-oju-terra/12 bg-oju-paz-claro uppercase text-white"/></label><Button className="bg-oju-verde text-oju-branco hover:bg-oju-verde-profundo"><Search className="mr-2 h-4 w-4"/>Consultar status</Button></form>{submitted && <div className="mt-6 border-t border-oju-terra/10 pt-6">{tracking.isLoading ? <p className="text-sm text-oju-terra-suave">Consultando com reserva…</p> : tracking.data ? <div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-oju-dende">Situação atual</p><p className="mt-3 font-serif text-4xl">{labels[tracking.data.status]}</p><p className="mt-4 text-sm text-oju-terra-suave">Atualizado em {new Date(tracking.data.updatedAt).toLocaleString("pt-BR")}. Se precisar complementar o pedido, use o mesmo canal seguro informado na solicitação.</p></div> : <p className="text-sm leading-6 text-oju-terra-suave">Não foi possível localizar este protocolo. Confira o código recebido após o envio ou registre uma nova solicitação se necessário.</p>}</div>}<Link href="/cuidado-e-consentimento" className="mt-7 inline-block text-xs font-bold uppercase tracking-[.1em] text-oju-dende">Registrar nova solicitação</Link></section></main></div>; }
