import { PublicHeader } from "@/components/PublicHeader";
import { useEditorialLive } from "@/hooks/useEditorialLive";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Search as SearchIcon } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const inputClass = "h-11 rounded border border-white/15 bg-white/5 px-3 text-sm text-white placeholder:text-white/35 focus:border-[#ef9e59] focus:outline-none";

export default function Search() {
  const [query, setQuery] = useState(""); const [themeId, setThemeId] = useState(""); const [territoryId, setTerritoryId] = useState(""); const [typeId, setTypeId] = useState(""); const [start, setStart] = useState(""); const [end, setEnd] = useState("");
  const filter = useMemo(() => ({ query: query || undefined, themeId: themeId ? Number(themeId) : undefined, territoryId: territoryId ? Number(territoryId) : undefined, contentTypeId: typeId ? Number(typeId) : undefined, startDate: start ? new Date(`${start}T00:00:00`) : undefined, endDate: end ? new Date(`${end}T23:59:59`) : undefined }), [query, themeId, territoryId, typeId, start, end]);
  const { data: taxonomy } = trpc.editorial.taxonomies.useQuery(); const { data, isLoading } = trpc.editorial.search.useQuery(filter, { refetchInterval: 30000 }); const utils = trpc.useUtils(); useEditorialLive(() => { utils.editorial.search.invalidate(); });
  const options = (dimension: string) => taxonomy?.filter(item => item.dimension === dimension) || [];
  return <div className="min-h-screen bg-[#070605] text-white"><PublicHeader cinematic /><main className="container pb-16 pt-32"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ef9e59]">Acervo Ojú</p><h1 className="mt-4 font-serif text-5xl sm:text-6xl">Pesquisa documental</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-white/60">Encontre histórias, coberturas, documentários, projetos e coleções por território, tema, tipo e período.</p><div className="mt-10 grid gap-3 lg:grid-cols-[1.4fr_repeat(3,1fr)]"><div className="flex gap-2"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Palavra-chave" className={`w-full ${inputClass}`} /><button className="grid h-11 w-11 place-items-center rounded bg-[#ed9c58] text-[#24140b]"><SearchIcon className="h-4 w-4" /></button></div><select className={inputClass} value={themeId} onChange={event => setThemeId(event.target.value)}><option value="">Todo tema</option>{options("Tema").map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={territoryId} onChange={event => setTerritoryId(event.target.value)}><option value="">Todo território</option>{options("Território").map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={inputClass} value={typeId} onChange={event => setTypeId(event.target.value)}><option value="">Todo tipo</option>{options("Tipo de conteúdo").map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="mt-3 flex flex-wrap items-center gap-3 text-sm text-white/60"><span className="font-medium text-white">Período</span><input type="date" value={start} onChange={event => setStart(event.target.value)} className={inputClass} /><span>até</span><input type="date" value={end} onChange={event => setEnd(event.target.value)} className={inputClass} /></div><div className="mt-12 grid gap-3 md:grid-cols-2">{isLoading ? <p className="text-white/60">Buscando no acervo...</p> : data?.length ? data.map(item => <Link key={item.id} href={`/historias/${item.slug}`} className="group rounded border border-white/15 bg-[#100d0a] p-5 transition hover:border-[#ef9e59]/75"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ef9e59]">{item.contentKind}</p><h2 className="mt-3 font-serif text-3xl">{item.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/60">{item.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[#ef9e59]">Ver conteúdo <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>) : <p className="rounded border border-dashed border-white/20 p-8 text-white/60">Nenhum conteúdo publicado corresponde aos filtros escolhidos.</p>}</div></main></div>;
}
