import { ArrowRight, BookOpenText } from "lucide-react";
import { Link } from "wouter";
import { PublicHeader } from "@/components/PublicHeader";
import { portalContentDefaults, type HeroContent, usePortalContent } from "@/lib/portalContent";
import { trpc } from "@/lib/trpc";

export default function StoriesPreview() {
  const { data, isLoading } = trpc.editorial.search.useQuery({}, { refetchInterval: 30000 });
  const stories = (data || []).filter(item => item.contentKind === "História");
  const content = usePortalContent("Histórias");
  const hero = content.block<HeroContent>("hero", portalContentDefaults.Histórias.hero as HeroContent);
  return <div className="min-h-screen bg-[#070605] text-white"><PublicHeader cinematic /><main className="container pb-20 pt-32">{hero && <section className="grid gap-8 border-b border-white/10 pb-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#ef9e59]">{hero.eyebrow}</p><h1 className="mt-5 max-w-4xl font-serif text-5xl leading-[.94] sm:text-7xl">{hero.title}</h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/65">{hero.description}</p></div><aside className="border-l border-[#ef9e59]/45 pl-6"><BookOpenText className="h-7 w-7 text-[#ef9e59]" /><p className="mt-5 font-serif text-2xl">Cada leitura pode levar a outras camadas: tema, território, memória e acervo.</p></aside></section>}{isLoading ? <p className="mt-12 text-sm text-white/60">Organizando histórias…</p> : stories.length ? <section className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{stories.map(story => <Link key={story.id} href={`/historias/${story.slug}`} className="group border border-white/15 bg-[#100d0a] p-6 transition hover:border-[#ef9e59]/75"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ef9e59]">História documental</p><h2 className="mt-5 font-serif text-3xl leading-[1.03]">{story.title}</h2>{story.summary && <p className="mt-4 line-clamp-3 text-sm leading-6 text-white/65">{story.summary}</p>}<span className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#ef9e59]">Ler história <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</section> : <section className="mt-12 border border-dashed border-white/20 bg-[#0c0907] p-10"><h2 className="font-serif text-3xl">A primeira história ainda está sendo preparada.</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-white/60">A Ojú publica com tempo, revisão e contexto. Quando uma história estiver pronta, ela aparecerá aqui ligada às suas relações documentais.</p><Link href="/memorias-documentais" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.1em] text-[#ef9e59]">Conhecer as memórias documentais <ArrowRight className="h-4 w-4" /></Link></section>}</main></div>;
}
