FROM node:22-bookworm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
COPY patches ./patches
RUN npm install -g corepack@latest && corepack pnpm install --frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["corepack", "pnpm", "dev"]
