import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { MapPinned } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const documentaryDimensions = ["Território", "Localização", "Pessoa/organização", "Evento", "Tema"] as const;
export function CoverageTaxonomiesPanel({ publicationId, version, initialIds }: { publicationId: number; version: number; initialIds: number[] }) { const utils = trpc.useUtils(); const { data } = trpc.editorial.taxonomies.useQuery(); const [selected, setSelected] = useState<number[]>(initialIds); useEffect(() => setSelected(initialIds), [initialIds.join(",")]); const save = trpc.editorial.update.useMutation({ onSuccess: () => { toast.success("Relações documentais salvas."); utils.editorial.preview.invalidate({ id: publicationId }); utils.editorial.adminList.invalidate(); }, onError: error => toast.error(error.message) }); const grouped = documentaryDimensions.map(dimension => [dimension, data?.filter(item => item.dimension === dimension) || []] as const); const toggle = (id: number) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]); return <section className="admin-card mt-8 p-6"><div className="flex gap-3"><div className="rounded-xl bg-[#f6d978] p-3"><MapPinned className="h-5 w-5" /></div><div><p className="font-serif text-2xl">Relações documentais</p><p className="mt-1 text-sm text-[#655e52]">Conecte esta Cobertura ao território, local, casa/organização, evento e tema. Esses vínculos serão exibidos na prévia e no portal.</p></div></div><div className="mt-6 grid gap-5 md:grid-cols-2">{grouped.map(([dimension, entries]) => <div key={dimension}><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#806817]">{dimension}</p><div className="mt-3 space-y-2">{entries.length ? entries.map(item => <label key={item.id} className="flex cursor-pointer items-start gap-2 rounded-lg border border-[#242017]/10 bg-white p-3 text-sm"><Checkbox checked={selected.includes(item.id)} onCheckedChange={() => toggle(item.id)} /><span><strong>{item.name}</strong>{item.description && <span className="mt-1 block text-xs text-[#655e52]">{item.description}</span>}</span></label>) : <p className="text-sm text-[#756e60]">Cadastre itens em Territórios e taxonomias.</p>}</div></div>)}</div><div className="mt-6 flex justify-end"><Button disabled={save.isPending} onClick={() => save.mutate({ id: publicationId, expectedVersion: version, taxonomyIds: selected })} className="bg-[#242017] text-white">{save.isPending ? "Salvando..." : "Salvar relações documentais"}</Button></div></section>; }
