import { useAuth } from "@/_core/hooks/useAuth";
import { BadgeCheck, CircleDollarSign, Clock3, HandCoins, Landmark } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { AdminPage, EmptyAdmin } from "./_shared";

const money = (value: number | string) => Number(value).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const statusTone = { Pendente: "bg-[#f5e5de] text-[#8b4d24]", Parcial: "bg-[#fff1ca] text-[#8b6200]", Pago: "bg-[#e6f2e5] text-[#496b3b]" } as const;

export default function EarningsAdmin() {
  const { user } = useAuth(); const principal = user?.role === "administrador principal";
  const earnings = trpc.financial.earnings.useQuery(undefined, { refetchInterval: 7000 });
  const summary = earnings.data?.summary;
  return <AdminPage eyebrow={principal ? "Visão consolidada da rede" : "Minha carteira financeira"} title={principal ? "Ganhos, captações e repasses." : "Meus ganhos e repasses."}>
    <p className="-mt-5 mb-7 max-w-3xl text-sm leading-6 text-[#655e52]">Cada linha representa uma participação de captação já registrada. O valor esperado é diferente do valor pago: o status de repasse é confirmado exclusivamente pelo Super Admin e permanece auditável.</p>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{ label: "Participação esperada", value: summary?.expected ?? 0, icon: CircleDollarSign }, { label: "Repasses pagos", value: summary?.paid ?? 0, icon: BadgeCheck }, { label: "Repasses parciais", value: summary?.partial ?? 0, icon: HandCoins }, { label: "Pendente de repasse", value: summary?.pending ?? 0, icon: Clock3 }].map(({ label, value, icon: Icon }) => <article key={label} className="admin-card p-5"><Icon className="h-5 w-5 text-[#806817]" /><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-[#806817]">{label}</p><p className="mt-2 font-serif text-3xl">{money(value)}</p></article>)}</section>
    {principal ? <section className="admin-card mt-7 p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#806817]">Distribuição por administrador</p><h2 className="mt-2 font-serif text-3xl">Participações da rede.</h2>{earnings.data?.byAdministrator.length ? <div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{earnings.data.byAdministrator.map(item => <article key={item.userId} className="rounded-xl border border-[#242017]/10 bg-white p-4"><p className="font-medium text-[#393328]">{item.name}</p><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><span>Esperado<br /><b>{money(item.expected)}</b></span><span className="text-[#496b3b]">Pago<br /><b>{money(item.paid)}</b></span><span className="text-[#8b6200]">Parcial<br /><b>{money(item.partial)}</b></span><span className="text-[#8b4d24]">Pendente<br /><b>{money(item.pending)}</b></span></div></article>)}</div> : <p className="mt-4 text-sm text-[#655e52]">Nenhuma participação de captação registrada.</p>}</section> : null}
    <section className="admin-card mt-7 overflow-hidden"><div className="border-b border-[#242017]/10 p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#806817]">Lançamentos da carteira</p><h2 className="mt-2 font-serif text-3xl">Captações e visibilidades atribuídas.</h2></div>{earnings.isLoading ? <p className="p-6 text-sm text-[#655e52]">Carregando ganhos...</p> : earnings.data?.items.length ? <div className="overflow-x-auto"><table className="min-w-[860px] w-full text-left text-sm"><thead className="bg-[#eee9dc] text-[11px] uppercase tracking-[.12em] text-[#655e52]"><tr><th className="px-5 py-3">Origem</th><th className="px-4 py-3">Responsável</th><th className="px-4 py-3">Política</th><th className="px-4 py-3">Participação</th><th className="px-5 py-3">Repasse</th></tr></thead><tbody>{earnings.data.items.map(item => <tr key={`${item.sourceType}-${item.id}`} className="border-t border-[#242017]/10"><td className="px-5 py-4"><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-[#655e52]">{item.sourceType} · {item.detail}</p></td><td className="px-4 py-4 text-xs text-[#655e52]">{principal ? item.recipientName : "Minha carteira"}</td><td className="px-4 py-4 text-xs text-[#655e52]">{item.policyVersion ? `Versão ${item.policyVersion}` : "Regra anterior"}</td><td className="px-4 py-4 font-semibold">{money(item.amount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone[item.status]}`}>{item.status}</span></td></tr>)}</tbody></table></div> : <EmptyAdmin text="Ainda não há captações com participação financeira nesta carteira." />}</section>
  </AdminPage>;
}
