import { Archive, BookOpenText, Camera, Clapperboard, Film, FolderKanban, MapPinned, Plus, Video } from "lucide-react";
import { Link } from "wouter";
import { AdminPage } from "./_shared";

const fronts = [
  { title: "Histórias", description: "Narrativas em texto, foto e vídeo relacionadas ao território.", icon: BookOpenText, href: "/admin/publicacoes?tipo=História", action: "Criar História" },
  { title: "Coberturas", description: "Eventos, celebrações, relações institucionais e registro audiovisual.", icon: Video, href: "/admin/publicacoes?tipo=Cobertura", action: "Criar Cobertura" },
  { title: "Documentários", description: "Filmes e peças audiovisuais com texto, fotos, vídeo e créditos completos.", icon: Clapperboard, href: "/admin/publicacoes?tipo=Documentário", action: "Criar Documentário" },
  { title: "Projetos", description: "Iniciativas, séries e ações documentais que podem reunir múltiplas mídias.", icon: FolderKanban, href: "/admin/publicacoes?tipo=Projeto", action: "Criar Projeto" },
  { title: "Fotografia documental", description: "Coleções de até cinco fotografias, cada uma com data, local e biografia viva.", icon: Camera, href: "/admin/publicacoes?tipo=Fotografia%20documental", action: "Criar coleção" },
  { title: "Territórios", description: "Dados vivos de localização, evento, tema, organização e relações documentais.", icon: MapPinned, href: "/admin/taxonomias", action: "Organizar Territórios" },
  { title: "Acervo e miniclipes", description: "Fotos, vídeos e direitos de mídia reutilizáveis, inclusive para o fundo vivo da Home.", icon: Archive, href: "/admin/midias", action: "Abrir Acervo" },
];

export default function EditorialFrontsAdmin() { return <AdminPage eyebrow="Frentes editoriais" title="Cada formato com seu próprio começo, meio e fim."><p className="-mt-4 max-w-3xl text-sm leading-6 text-[#655e52]">Todos os conteúdos seguem o mesmo ciclo editorial, mas cada frente começa com o tipo correto e permite texto, fotos, vídeos, créditos, direitos e relações documentais conforme o escopo.</p><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{fronts.map(front => <article key={front.title} className="admin-card flex min-h-60 flex-col p-6"><front.icon className="h-6 w-6 text-[#806817]" /><h2 className="mt-8 font-serif text-3xl">{front.title}</h2><p className="mt-3 text-sm leading-6 text-[#655e52]">{front.description}</p><Link href={front.href} className="mt-auto inline-flex items-center gap-2 pt-7 text-sm font-bold text-[#806817]"><Plus className="h-4 w-4" />{front.action}</Link></article>)}</div><section className="admin-card mt-7 grid gap-4 p-6 md:grid-cols-3"><p className="text-sm leading-6 text-[#655e52]"><strong className="text-[#242017]">1. Criar.</strong> Escolha a frente e defina título, equipe, texto e limites de mídia.</p><p className="text-sm leading-6 text-[#655e52]"><strong className="text-[#242017]">2. Documentar.</strong> Anexe fotos ou vídeos do Acervo e relacione território, evento, tema e organização.</p><p className="text-sm leading-6 text-[#655e52]"><strong className="text-[#242017]">3. Publicar.</strong> Revise, aprove e publique; a curadoria decide onde o conteúdo aparece no portal.</p></section><section className="mt-4 grid gap-4 rounded-2xl border border-[#806817]/25 bg-[#fff7dc] p-6 md:grid-cols-[auto_1fr_auto]"><Film className="h-7 w-7 text-[#806817]" /><div><p className="font-serif text-2xl">Vídeos curtos e miniclipes</p><p className="mt-2 text-sm leading-6 text-[#655e52]">Em Histórias, Coberturas, Documentários e Projetos, um miniclipe é anexado como vídeo do Acervo e segue os mesmos direitos, limites e ciclo editorial. Já o miniclipe de fundo vivo da Home é selecionado separadamente para não confundir vitrine visual com conteúdo publicado.</p></div><Link href="/admin/miniclipes" className="inline-flex items-center gap-2 self-center text-sm font-bold text-[#806817]"><Film className="h-4 w-4" />Gerenciar fundo vivo</Link></section></AdminPage>; }
