import DashboardLayout from "@/components/DashboardLayout";
import { ArrowLeft, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";

export default function HomePreview() {
  const [, params] = useRoute("/admin/home-preview/:id");
  const { data, isLoading } = trpc.editorial.preview.useQuery({ id: Number(params?.id) }, { enabled: Boolean(params?.id) });
  return <DashboardLayout><div className="mx-auto max-w-6xl"><Link href="/admin/destaques" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft className="h-4 w-4" />Voltar à Curadoria</Link>{isLoading ? <p className="mt-12">Montando a prévia da Home...</p> : data ? <section className="mt-8 overflow-hidden rounded-2xl border border-[#242017]/10 bg-[#f7f5ef]"><div className="flex items-center justify-between border-b border-[#242017]/10 px-6 py-4"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#806817]">Prévia da Home</p><span className="rounded-full bg-[#eee9dc] px-3 py-1 text-xs">{data.homePlacement}</span></div><div className="grid min-h-[390px] items-end gap-8 bg-[#242017] p-8 text-[#f7f5ef] md:grid-cols-[1.1fr_.9fr] md:p-12"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#f6c94c]">{data.contentKind}</p><h1 className="mt-5 max-w-2xl font-serif text-5xl leading-[.98]">{data.title}</h1><p className="mt-6 max-w-xl text-[#d7d0c3]">{data.summary || data.subtitle || "Sem descrição editorial."}</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-6"><Sparkles className="h-5 w-5 text-[#f6c94c]" /><p className="mt-10 font-serif text-2xl">{data.homePlacement === "Nenhum" ? "Este conteúdo não aparecerá em bloco de destaque." : `Posicionamento: ${data.homePlacement}.`}</p><p className="mt-3 text-sm leading-6 text-[#cfc6b6]">Relevância {data.relevance}/100 · Destaque manual {data.manualFeatured ? "ativo" : "inativo"} · Patrocinado {data.sponsored ? "sim" : "não"}.</p></div></div></section> : <p className="mt-12">Conteúdo não encontrado.</p>}</div></DashboardLayout>;
}
