import { CheckCheck, FilePenLine, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AdminPage, EmptyAdmin } from "./_shared";

export default function MemoryReviewAdmin() { const utils = trpc.useUtils(); const { data, isLoading } = trpc.community.listMemories.useQuery(undefined, { refetchInterval: 5000 }); const [openId, setOpenId] = useState<number | null>(null); const review = trpc.community.reviewMemoryAssistance.useMutation({ onSuccess: () => { utils.community.listMemories.invalidate(); setOpenId(null); } }); const candidates = data?.filter(item => item.generatedTranscript || item.generatedSummary) || [];
  return <AdminPage eyebrow="Memórias orais" title="Revisar assistência antes de publicar."><p className="-mt-5 mb-7 max-w-3xl text-sm leading-6 text-oju-terra-suave">A transcrição e o resumo são apenas uma base de trabalho. Revise contexto, termos próprios, nomes e trechos sensíveis; salvar esta etapa registra a revisão humana, mas não publica a memória.</p>{isLoading ? <p>Carregando memórias…</p> : candidates.length ? <div className="grid gap-5">{candidates.map(memory => <article key={memory.id} className="admin-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#806817]">{memory.theme || "Memória oral"}</p><h2 className="mt-2 font-serif text-3xl">{memory.title}</h2><p className="mt-2 text-sm text-oju-terra-suave">{memory.aiReviewedAt ? `Revisado em ${new Date(memory.aiReviewedAt).toLocaleString("pt-BR")}` : "Aguardando revisão humana"}</p></div><Button variant="outline" onClick={() => setOpenId(openId === memory.id ? null : memory.id)}><FilePenLine className="mr-2 h-4 w-4"/>{openId === memory.id ? "Fechar revisão" : "Revisar assistência"}</Button></div>{openId === memory.id && <form className="mt-6 grid gap-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); review.mutate({ id: memory.id, generatedTranscript: String(form.get("transcript")) || null, generatedSummary: String(form.get("summary")) || null }); }}><section className="rounded-xl border border-[#d49b4c]/40 bg-[#fff7e8] p-4"><div className="flex gap-2"><Sparkles className="h-5 w-5 shrink-0 text-[#8b4d24]"/><p className="text-sm leading-6 text-[#6b4a2b]">Texto gerado com assistência. Não acrescente informações não confirmadas; retire ou proteja trechos que não possam ser divulgados.</p></div></section><label className="grid gap-2 text-sm font-medium">Transcrição revisada<Textarea required name="transcript" defaultValue={memory.generatedTranscript || ""} className="min-h-64"/></label><label className="grid gap-2 text-sm font-medium">Resumo revisado<Textarea name="summary" defaultValue={memory.generatedSummary || ""} className="min-h-28"/></label><Button disabled={review.isPending} className="w-fit bg-oju-verde text-oju-branco"><CheckCheck className="mr-2 h-4 w-4"/>{review.isPending ? "Salvando..." : "Salvar revisão humana"}</Button></form>}</article>)}</div> : <EmptyAdmin text="Nenhuma transcrição assistida aguarda revisão na sua carteira."/>}</AdminPage>; }
