import { BellRing, CheckCheck, CircleDollarSign } from "lucide-react";
import { useEffect, useRef } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AdminPage, EmptyAdmin } from "./_shared";

export default function PayoutNotificationsAdmin() {
  const utils = trpc.useUtils(); const seen = useRef(new Set<number>()); const notices = trpc.financial.notifications.useQuery(undefined, { refetchInterval: 7000 }); const read = trpc.financial.markNotificationRead.useMutation({ onSuccess: () => utils.financial.notifications.invalidate(), onError: error => toast.error(error.message) }); const unread = notices.data?.filter(item => !item.readAt).length ?? 0;
  useEffect(() => { notices.data?.forEach(item => { if (!item.readAt && !seen.current.has(item.id)) { seen.current.add(item.id); toast.success(item.title, { description: item.message }); } }); }, [notices.data]);
  return <AdminPage eyebrow="Avisos financeiros" title="Repasses concluídos."><p className="-mt-5 mb-7 max-w-3xl text-sm leading-6 text-oju-terra-suave">Quando a Equipe Ojú marca um repasse de captação como pago, a Ojú registra este aviso na carteira responsável. O alerta não substitui comprovante ou conciliação financeira, mas preserva a comunicação operacional.</p><section className="admin-card mb-7 flex flex-wrap items-center justify-between gap-4 p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#f6d978] p-3"><BellRing className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#806817]">Caixa de avisos</p><h2 className="mt-1 font-serif text-3xl">{unread} aviso{unread === 1 ? " novo" : "s novos"}</h2></div></div><CircleDollarSign className="h-7 w-7 text-[#806817]" /></section>{notices.isLoading ? <p className="text-sm text-oju-terra-suave">Carregando avisos...</p> : notices.data?.length ? <div className="grid gap-4">{notices.data.map(item => <article key={item.id} className={`admin-card p-5 ${item.readAt ? "opacity-75" : "border-[#d49b4c]/50 bg-[#fffaf1]"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#806817]">{item.sourceType} · repasse {item.payoutStatus.toLowerCase()}</p><h2 className="mt-2 font-serif text-2xl">{item.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-oju-terra-suave">{item.message}</p><p className="mt-3 text-xs text-[#806817]">{new Date(item.createdAt).toLocaleString("pt-BR")}{item.recipientName ? ` · ${item.recipientName}` : ""}</p></div>{!item.readAt ? <Button size="sm" variant="outline" onClick={() => read.mutate({ id: item.id })} disabled={read.isPending}><CheckCheck className="mr-2 h-4 w-4" />Marcar como lido</Button> : <span className="text-xs font-semibold text-[#496b3b]">Lido</span>}</div></article>)}</div> : <EmptyAdmin text="Nenhum repasse concluído gerou aviso para esta carteira ainda." />}</AdminPage>;
}
