import { Eye, EyeOff, FilePenLine, Plus, RotateCcw, Save, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { portalPages, type PortalPage } from "@/lib/portalContent";
import { trpc } from "@/lib/trpc";
import { AdminPage } from "./_shared";

type EditorState = { id?: number; page: PortalPage; sectionKey: string; label: string; contentJson: string; isVisible: boolean; displayOrder: number };
const blankEditor = (): EditorState => ({ page: "Home", sectionKey: "novo-bloco", label: "Novo bloco do portal", contentJson: "{\n  \"title\": \"\",\n  \"description\": \"\"\n}", isVisible: true, displayOrder: 50 });

function toEditor(block: { id: number; page: PortalPage; sectionKey: string; label: string; contentJson: string; isVisible: boolean; displayOrder: number }) {
  let contentJson = block.contentJson;
  try { contentJson = JSON.stringify(JSON.parse(block.contentJson), null, 2); } catch { /* preserva o valor auditável original */ }
  return { id: block.id, page: block.page, sectionKey: block.sectionKey, label: block.label, contentJson, isVisible: block.isVisible, displayOrder: block.displayOrder };
}

export default function PortalContentAdmin() {
  const utils = trpc.useUtils();
  const { data: blocks, isLoading, error } = trpc.portalContent.adminList.useQuery();
  const [editor, setEditor] = useState<EditorState | null>(null);
  const activeBlocks = useMemo(() => (blocks || []).filter(block => !block.deletedAt), [blocks]);
  const save = trpc.portalContent.save.useMutation({ onSuccess: () => { toast.success("Conteúdo do portal salvo."); setEditor(null); utils.portalContent.adminList.invalidate(); utils.portalContent.publicByPage.invalidate(); }, onError: error => toast.error(error.message) });
  const visibility = trpc.portalContent.setVisibility.useMutation({ onSuccess: () => { toast.success("Visibilidade atualizada."); utils.portalContent.adminList.invalidate(); utils.portalContent.publicByPage.invalidate(); }, onError: error => toast.error(error.message) });
  const remove = trpc.portalContent.remove.useMutation({ onSuccess: () => { toast.success("Bloco excluído do portal. Ele pode ser restaurado pelo Super Admin."); utils.portalContent.adminList.invalidate(); utils.portalContent.publicByPage.invalidate(); }, onError: error => toast.error(error.message) });
  const restore = trpc.portalContent.restore.useMutation({ onSuccess: () => { toast.success("Bloco restaurado."); utils.portalContent.adminList.invalidate(); utils.portalContent.publicByPage.invalidate(); }, onError: error => toast.error(error.message) });

  function submit() {
    if (!editor) return;
    try { JSON.parse(editor.contentJson); } catch { toast.error("Revise a estrutura do conteúdo: o JSON não está válido."); return; }
    save.mutate(editor);
  }

  if (error) return <AdminPage eyebrow="Conteúdo institucional" title="Conteúdo do portal" action={null}><section className="admin-card p-8"><p className="font-serif text-2xl">Apenas o Super Admin pode administrar estes blocos.</p><p className="mt-3 max-w-2xl text-sm leading-6 text-[#655e52]">A edição de textos, serviços, método, CTAs e ordem do portal fica concentrada nesta área protegida.</p></section></AdminPage>;

  return <AdminPage eyebrow="Conteúdo institucional" title="Conteúdo do portal" action={<Button onClick={() => setEditor(blankEditor())} className="bg-[#242017] text-white"><Plus className="mr-2 h-4 w-4" />Novo bloco</Button>}>
    <section className="admin-card p-6"><div className="flex gap-3"><div className="rounded-xl bg-[#f6d978] p-3"><FilePenLine className="h-5 w-5" /></div><div><p className="font-serif text-2xl">Textos, serviços e método sem código.</p><p className="mt-1 max-w-3xl text-sm leading-6 text-[#655e52]">Só o Super Admin edita a Home nacional e os blocos institucionais do portal. Parceiros operam conteúdo do território — não esta curadoria. Ao abrir esta página, os blocos padrão passam a aparecer na lista para edição.</p></div></div></section>
    {editor && <section className="admin-card mt-6 p-6"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-[#242017]/10 pb-5"><div><p className="editorial-kicker">{editor.id ? "Editar bloco" : "Novo bloco"}</p><h2 className="mt-2 font-serif text-3xl">{editor.label || "Conteúdo institucional"}</h2></div><Button variant="outline" onClick={() => setEditor(null)}>Cancelar</Button></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="grid gap-2"><Label>Página</Label><select value={editor.page} onChange={event => setEditor({ ...editor, page: event.target.value as PortalPage })} className="h-10 rounded-md border border-[#242017]/20 bg-white px-3 text-sm">{portalPages.map(page => <option key={page} value={page}>{page}</option>)}</select></label><label className="grid gap-2"><Label>Nome interno do bloco</Label><Input value={editor.label} onChange={event => setEditor({ ...editor, label: event.target.value })} /></label><label className="grid gap-2"><Label>Chave técnica</Label><Input value={editor.sectionKey} onChange={event => setEditor({ ...editor, sectionKey: event.target.value })} /><span className="text-xs text-[#655e52]">Use letras minúsculas, números e hífen; não mude chaves existentes sem revisar a página correspondente.</span></label><label className="grid gap-2"><Label>Ordem de exibição</Label><Input type="number" min="0" value={editor.displayOrder} onChange={event => setEditor({ ...editor, displayOrder: Number(event.target.value) || 0 })} /></label><label className="flex items-center gap-3 text-sm font-medium md:col-span-2"><input type="checkbox" checked={editor.isVisible} onChange={event => setEditor({ ...editor, isVisible: event.target.checked })} className="h-4 w-4 accent-[#242017]" />Exibir este bloco no portal público</label><label className="grid gap-2 md:col-span-2"><Label>Conteúdo estruturado</Label><Textarea value={editor.contentJson} onChange={event => setEditor({ ...editor, contentJson: event.target.value })} className="min-h-72 font-mono text-xs leading-5" /><span className="text-xs leading-5 text-[#655e52]">Textos simples usam campos como <code>title</code> e <code>description</code>. Coleções usam <code>items</code>. O painel valida a estrutura antes de salvar.</span></label></div><Button onClick={submit} disabled={save.isPending} className="mt-6 bg-[#242017] text-white"><Save className="mr-2 h-4 w-4" />{save.isPending ? "Salvando…" : "Salvar conteúdo"}</Button></section>}
    <section className="mt-6 space-y-4">{isLoading ? <div className="admin-card p-8 text-sm text-[#655e52]">Carregando blocos do portal…</div> : portalPages.map(page => { const pageBlocks = (blocks || []).filter(block => block.page === page); if (!pageBlocks.length) return null; return <div key={page} className="admin-card overflow-hidden"><div className="border-b border-[#242017]/10 bg-[#f7f5ef] px-6 py-4"><p className="editorial-kicker">{page}</p></div><div className="divide-y divide-[#242017]/10">{pageBlocks.map(block => <article key={block.id} className={`flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between ${block.deletedAt ? "bg-[#f2efe7] opacity-70" : "bg-white"}`}><div><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{block.label}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-[.08em] ${block.deletedAt ? "bg-[#ddd6ca] text-[#625c50]" : block.isVisible ? "bg-[#d8eadc] text-[#2c683b]" : "bg-[#eee4c8] text-[#695411]"}`}>{block.deletedAt ? "Excluído" : block.isVisible ? "Visível" : "Oculto"}</span></div><p className="mt-1 text-xs text-[#655e52]">Chave: {block.sectionKey} · Ordem: {block.displayOrder}</p></div><div className="flex flex-wrap gap-2">{block.deletedAt ? <Button size="sm" variant="outline" onClick={() => restore.mutate({ id: block.id })}><RotateCcw className="mr-1 h-3.5 w-3.5" />Restaurar</Button> : <><Button size="sm" variant="outline" onClick={() => setEditor(toEditor(block as Parameters<typeof toEditor>[0]))}><FilePenLine className="mr-1 h-3.5 w-3.5" />Editar</Button><Button size="sm" variant="outline" onClick={() => visibility.mutate({ id: block.id, isVisible: !block.isVisible })}>{block.isVisible ? <><EyeOff className="mr-1 h-3.5 w-3.5" />Ocultar</> : <><Eye className="mr-1 h-3.5 w-3.5" />Exibir</>}</Button><Button size="sm" variant="outline" className="text-[#9d2b20]" onClick={() => remove.mutate({ id: block.id })}><Trash2 className="mr-1 h-3.5 w-3.5" />Excluir</Button></>}</div></article>)}</div></div>; })}</section>
    {activeBlocks.length === 0 && !isLoading && <section className="admin-card mt-6 p-8 text-sm text-[#655e52]">Nenhum bloco ativo está disponível. Crie um bloco para começar a organizar o conteúdo institucional.</section>}
  </AdminPage>;
}
