import { ArrowRight, MapPin } from "lucide-react";
import { Link } from "wouter";
import { PublicHeader } from "@/components/PublicHeader";
import { trpc } from "@/lib/trpc";

type Front = { kind: "Cobertura" | "Documentário" | "Projeto"; eyebrow: string; title: string; description: string; empty: string };

export function EditorialFrontPublic({ front }: { front: Front }) {
  const { data, isLoading } = trpc.editorial.search.useQuery({}, { refetchInterval: 30000 });
  const contents = data?.filter(item => item.contentKind === front.kind) || [];
  return <div className="min-h-screen bg-[#070605] text-white"><PublicHeader cinematic /><main className="container pb-16 pt-32"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ef9e59]">{front.eyebrow}</p><h1 className="mt-4 max-w-3xl font-serif text-6xl leading-[.95] sm:text-7xl">{front.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/65">{front.description}</p>{isLoading ? <p className="mt-14 text-white/60">Organizando conteúdos...</p> : contents.length ? <div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{contents.map((content, index) => <Link href={`/historias/${content.slug}`} key={content.id} className="group relative min-h-72 overflow-hidden rounded border border-white/15 bg-[#100d0a] p-5 transition hover:border-[#ef9e59]/80"><div className={`absolute inset-0 ${index % 3 === 0 ? "bg-[radial-gradient(circle_at_80%_20%,rgba(201,125,61,.45),transparent_26%),linear-gradient(135deg,#17110d,#070605)]" : index % 3 === 1 ? "bg-[linear-gradient(135deg,#15100c,#6c3f20,#080706)]" : "bg-[radial-gradient(circle_at_20%_75%,rgba(160,91,45,.5),transparent_26%),linear-gradient(135deg,#100d0a,#1b120d)]"}`} /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/25 to-transparent" /><div className="relative flex h-full flex-col justify-end"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#ef9e59]">{front.kind}</p><h2 className="mt-3 font-serif text-3xl leading-[1.05]">{content.title}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-white/65">{content.summary}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[#ef9e59]"><MapPin className="h-4 w-4" />Abrir conteúdo <ArrowRight className="h-4 w-4" /></span></div></Link>)}</div> : <section className="mt-14 rounded border border-dashed border-white/20 bg-[#100d0a] p-10"><p className="font-serif text-3xl">{front.empty}</p><p className="mt-3 max-w-xl text-sm leading-6 text-white/60">Quando a equipe publicar materiais desta frente, eles aparecerão aqui com texto, fotografia, vídeo e relações documentais conforme o conteúdo.</p><Link href="/contrate-sua-cobertura" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-[#ef9e59]">Registrar uma cobertura <ArrowRight className="h-4 w-4" /></Link></section>}</main></div>;
}
